Dockerfile, Makefile, README.md, cephfs/cephfs_test.go, ci/entrypoint.sh, doc.go, rados/rados_test.go, rbd/rbd.go, rbd/rbd_test.go
noahdesu -> ceph
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
=> repo: update new repo path

rados/ioctx.go, rados/rados_test.go
>Hi @kallax this looks good, and I'd like to merge it. Two comments. First, you might consider creating 
>a separate test for append, rather than making an existing test large. Second, can you submit this 
>pull request at http://github.com/ceph/go-ceph, we've moved development over to that repository.
hi,
thanks for the response.
per your feedback, i've now forked from http://github.com/ceph/go-ceph, and added the append test as a separate test.
please let me know if this is ok for inclusion.
best,
emmet
=> added append function and a test

Dockerfile, rados/conn.go
Explanation of the problem is described in issue #10.
=> Fix MonCommand() to support Go 1.6

.gitignore, rados/conn.go, rados/rados_test.go
Implementation for https://github.com/ceph/go-ceph/issues/24
=> Add support for mon_command input buffer

rados/ioctx.go
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> ioctx: compiles on osx

rados/ioctx.go
=> fix panic when writing empty objects

rados/ioctx.go, rbd/rbd.go
Some Go / cgo style cleanups that have been niggling me for a few days ;-)
=> Code cleanups

.travis.yml, Makefile
=> Enable golint in travis and Makefile

rados/conn.go, rados/rados_test.go
Add missing functions that can be of use for the Ceph-CSI project.
Fixes: #94
=> Add support for rados_pool_lookup() and rados_pool_reverse_lookup()

.travis.yml, micro-osd.sh
Support testing with nautilus and add nautilus to the test matrix for travis ci.
Fixes #103
=> Add nautilus to the travis test matrix

doc.go, package_test.go
The .go files in the root of the project seemed a bit crufty and neglected, clean them up a bit.
=> Clean up root directory .go files a bit

cephfs/cephfs.go, rados/conn.go
It doesn't make sense for a library to just print text. :-)
=> Remove print and logging calls from library.

rados/rados_test.go
Keeping the _test.go code in the same package allows for the testing
of private functions. AFAIK it is more conventional as well.
=> rados: include rados_test.go in rados package

rbd/rbd.go, rbd/rbd_test.go
The arguments passed to Copy() would normally be pointers, just like it
is done with other similar functions. This never worked correctly, as
the arguments were not validated correctly (not recognized) and the
error "Must specify either destination pool or destination image" always
got returned.
Modifying Image.Copy() into something usable would result in a complete
rewrite. Instead of a single Image.Copy() function that tries to cover
rbd_copy() and rbd_copy2(), provide Image.Copy() and Image.Copy2() so
that the API matches the librbd.so interface.
=> rbd: fix broken Image.Copy() and add an exhaustive test for it

rbd/rbd.go, rbd/rbd_test.go
rbd: add metadata functions on image to get, set, remove metadata
=> rbd: add metadata functions on image to get, set, remove metadata

rbd/rbd_test.go
In order to get a higher test coverage for rbd/rbd.go, there is a need
to trigger errors for the librbd functions. This makes it possible to
test the error path. The new TestClosedImage() function tricks
RbdImage.validate() into accepting an image that is closed, but still
references the closed image.
librbd is expected to return an error when the image is closed. However,
passing a closed image does not result in stable behavior. Sometimes
librbd causes a panic, at other times there will be a hang and the test
will time-out.
The TestClosedImage() function is disabled, it will skip all testing but
remains available so that it could be enabled in the future.
=> rbd/tests: force librbd errors by passing a closed image

rados/rados_test.go
Improve coverage for a number of various functions in the rados package. Most of these are related to error handling or other code branches that were not being checked.
=> rados: improve test coverage

rados/conn.go, rados/ioctx.go, rados/rados.go
Improve a fair number of missing or incorrectly formed doc comments in the rados package.
=> rados doc improvements

rbd/rbd.go, rbd/rbd_test.go
Change is based off of the branch tracked by PR #146 . Please review that PR first.
Add a new CloneImage that makes use of rbd_clone3 and thus behaves like
the new CreateImage function.
=> rbd: add CloneImage as a wrapper for rbd_clone3 func

cephfs/cephfs.go
Minor doc comment improvements for cephfs pkg.
=> cephfs: doc comment improvements

rbd/rbd_test.go
=> rbd: fix some tests that ignore error results.

.github/workflows/main.yml, Makefile
Experiment with using github workflow/actions for ci.
=> ci: add a test github workflow/actions

cephfs/file.go, cephfs/file_test.go
Added ceph_flock() function which applies or removes an advisory lock on an open file.
Fixes: https://github.com/ceph/go-ceph/issues/248
=> cephfs: add ceph_flock() function

cephfs/path.go, cephfs/path_test.go
Rename, it does what it says on the tin. Tests included.
=> cephfs: add Rename function

README.md, docs/hints.md
I've tried to spruce up the README.md file a bit. The major changes are a new, but short, introductory section and I've moved some of the "documentation" to a secondary page as they were more hints/tips-n-tricks level stuff than complete docs. Commit messages all have more detail.
=> readme: Various improvements

cephfs/admin/clone.go
Improve the docs for CloneSubVolumeSnapshot.
=> cephfs admin: doc comment improvements for clone

cephfs/admin/volume.go, cephfs/admin/volume_test.go
For users who need to know the pools (by name) as well as the files
systems, we add ListFileSystems which is similar to 'ceph fs ls', rather
than the existing ListVolumes as that function is simlar to 'ceph fs
volume ls' and that does not return pool information.
Fixes: #375
=> cephfs admin: add ListFileSystems function for listing fs with pools

.github/workflows/main.yml
We could probably have done this sooner, but now is better than later.
=> ci: remove "luminous" from testing matrix

README.md
=> readme: document v0.7.0 and the ceph versions it supports

Makefile
$ make test-docker
grep: /sys/kernel/security/lsm: No such file or directory
Signed-off-by: Yang Honggang <yanghonggang@kuaishou.com>
=> Makefile: fix "No such file or directory" error

rbd/rbd_test.go
Using WriteSame() to implement a zerofill function is less straight
forward than expected. `rbd_discard_on_zeroed_write_same` is a Ceph
option than affects the behaviour of WriteSame(). By default the option
is enabled, causing WriteSame() to call discard instead of writing
zeros.
=> rbd: Add TestWriteSame/zerofill test case

cephfs/admin/subvolume.go, cephfs/admin/subvolume_test.go
=> cephfs: add state field to SubVolumeInfo structure.

internal/cutil/ptrguard_test.go
This adds a test that assures that the special //go:uintptrescapes comment
before the storeUntilRelease() function works as intended, that is the
garbage collector doesn't touch the object referenced by the uintptr until
the function returns after Release() is called.  The test will fail if the
//go:uintptrescapes comment is disabled (removed) or stops working in future
versions of go.
=> ptrguard: assert that //go:uintptrescapes actually works

internal/cutil/ptrguard.go
Uintptr are guaranteed to be at least of the size of a pointer.  However, in
theory it could be larger.  Since the code of PtrGuard assumes both have the
same size and to be on the safe side, this change adds a compile-time check,
that the sizes of uintptr and pointers are the same.
Signed-off-by: Sven Anderson <sven@anderson.de>
=> ptrguard: assert pointer and uintptr have same size

rbd/mirror.go, rbd/mirror_test.go
The MirrorImageStatusSummary returns a map of image mirroring states to
the number of images in those states or an error.
Tests of both the basic conditions and actual mirrored images are added.
Fixes #484 
To the best of my knowledge, this is the core API call for `rbdmirror pool status` from  #398, but that cli command does other stuff too, and so I hesitate to suggest this PR resolves that issue.
=> rbd: add MirrorImageStatusSummary implementing rbd_mirror_image_status_summary

cephfs/permissions.go, cephfs/permissions_test.go
Signed-off-by: RAJAT SINGH <rajasing@redhat.com>
Added wrapper for lchown that was missing. Fixes #262
=> cephfs: add wrapper for ceph_lchown

cephfs/cephfs_test.go, cephfs/file_test.go, entrypoint.sh, internal/cutil/iovec_test.go, internal/cutil/sync_buffer_test.go
=> tests: add benchmarks for PtrGuard related types

rbd/mirror.go, rbd/mirror_test.go
* Add SetMirrorSiteName implementing rbd_mirror_site_name_set
* Add GetMirrorSiteName implementing rbd_mirror_site_name_get
These functions are used to set the name of the site (for an entire
cluster) for rbd mirroring purposes. It's a bit strange that it's
part of rbd and not rados, but such is life.
Tests included.
Fixes #487
=> rbd: add SetMirrorSiteName and GetMirrorSiteName functions

rbd/rbd.go, rbd/rbd_test.go
With rbd_deep_copy() an image can be copied with selected options. This
can be used to create a copy and flatten the image in one go.
Updates: ceph/ceph-csi#2077
=> rbd: add DeepCopy()

rbd/mirror.go, rbd/mirror_test.go
Depends on #494 
Resolves #485 
* Add CreateMirrorPeerBootstrapToken implementing rbd_mirror_peer_bootstrap_create
* Add ImportMirrorPeerBootstrapToken implementing rbd_mirror_peer_bootstrap_import
These functions can be used to set up mirroring between pools. Basic tests     included. The tests only verify that functions work, not that they     actually mirror data. That is a job for another day.
=> rbd: add CreateMirrorPeerBootstrapToken & ImportMirrorPeerBootstrapToken functions

rbd/mirror.go, rbd/mirror_test.go
Add a new "iterator" type to fetch global statuses for all images in a pool. This is implemented as an iterator as the API design in C and the python bindings in the ceph tree imply a desire to return many items, beyond the scale of an immediate list.
Resolves: #481
=> rbd: add a MirrorImageGlobalStatusIter implementing rbd_mirror_image_global_status_list

rbd/mirror.go, rbd/mirror_test.go
Fixes #488 
Add function rbd_mirror_uuid_get that is missing from go-ceph.
Signed-off-by: RAJAT SINGH <rajasing@redhat.com>
=> rbd : add missing API component

rgw/admin/bucket.go, rgw/admin/quota.go, rgw/admin/radosgw.go, rgw/admin/usage.go, rgw/admin/user.go
The http package provides constants for common http methods so let's use
them.
Signed-off-by: Sébastien Han <seb@redhat.com>
=> rgw/admin: use http verbs from the http package

internal/cutil/ptrguard_test.go
The finalizer of an object is called in a separate go routine, so we
might have to check several times for its completion.
Fixes: #545
=> cutil: fix race condition in ptrguard tests

rbd/mirror.go, rbd/mirror_test.go
This commit adds MirrorImageInstanceIDList and
MirrorImageInstanceIDIter with necessary helper functions
and tests.
Fixes: #483
Signed-off-by: Rakshith R <rar@redhat.com>
=> rbd: implement binding for rbd_mirror_image_instance_id_list

Makefile, testing/containers/ceph/Dockerfile
Update the file to reflect recent changes in both ceph and go. Details in the commit messages.
=> Updates to the go-ceph ci container image file

cephfs/cephfs.go, cephfs/cephfs_test.go
cephfs: add missing cephfs API Components: function ceph_version 
Signed-off-by: yjkim <oct28.yjkim@gmail.com]>
- [O] Added tests for features and functional changes
- [O] Public functions and types are documented
- [O] Standard formatting is applied to Go code
=> cephfs : add missing cephfs API components: fuction ceph_version

rados/rados_test.go
=> rados: add missing error asserts

rados/rados_test.go, rados/read_op_test.go, rados/snapshot_test.go, rados/write_op_test.go
=> rados: fix a couple of linter warnings

contrib/implements/internal/implements/cast.go
=> contrib: implements tool prints stderr if castxml fails

docs/api-status.json, rbd/rbd.go, rbd/rbd_test.go
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
=> rbd: export image name

docs/api-status.json, docs/api-status.md, rbd/admin/imagespec.go, rbd/admin/task.go, rbd/admin/task_test.go
Promoting ImageSpec & task apis to stable so
they can be release in v0.13.0.
Signed-off-by: Rakshith R <rar@redhat.com>
=> rbd/admin: promote ImageSpec & tasks api to stable

rgw/admin/README.md
the function `co.GetUser()` needs -
ctx and type user not string
Signed-off-by: rakeshgm <rakeshgm@redhat.com>
=> rgw/admin: correct example

README.md
=> readme: document v0.13.0 and the ceph versions it supports

.github/mergify.yml
Mergify has not been working for weeks as they removed support for the
deprecated style we were relying on. This is my first attempt to
update it to the new style.
=> github: update mergify.yml to new style

README.md
=> readme: note how to get supported packages on centos

rados/watcher.go
=> rados: add warning logs to watcher callbacks

docs/release-process.md
A work-in-progress expansion of the release process from the most minimum technical requirements to something that actually reflects the workflow I've used for the last year or so.
=> docs: document release processes in greater detail

internal/util/util.go, rgw/admin/bucket_test.go
=> rgw/admin: fix tests for quincy

README.md
=> readme: note v0.16.0 has preliminary quincy support

docs/api-status.json, docs/api-status.md, rados/rados_read_op_assert_version.go, rados/rados_read_op_assert_version_test.go, rados/rados_write_op_assert_version.go, rados/rados_write_op_assert_version_test.go, rados/rados_write_op_remove.go, rados/rados_write_op_remove_test.go, rados/rados_write_op_setxattr.go, rados/rados_write_op_setxattr_test.go, rados/read_op_omap_get_vals_by_keys.go, rados/read_op_omap_get_vals_by_keys_test.go, rados/read_op_read.go, rados/read_op_read_test.go, rados/watcher.go, rados/watcher_test.go
No issues raised for these apis during the preview period so making the apis stable in their expected stable version.
=> rados: stabilze some APIs

README.md
This is a replacement for #540.
=> Add MacOS instructions to README

Makefile, entrypoint.sh
Help ensure we have high quality shell scripts by checking them with `shellcheck`.
=> Run shellcheck on our shell scripts

.github/workflows/main.yml
When archiving, use the latest version of the archive action and use
it's ability to archive an entire directory.
=> workflows: update archive action

common/log/log.go, docs/api-status.json, docs/api-status.md, rados/rados_set_locator.go, rgw/admin/link.go, rgw/admin/subuser.go
=> go-ceph: change mature preview APIs to stable

README.md
=> go-ceph: update README.md for v0.17.0 release

README.md
=> go-ceph: update README.md for v0.18.0 release

README.md
Fixes #777
Let's review but not merge this until release day (or maybe the day before), to avoid potential confusion.
=> Update readme for next release (v0.19)

common/admin/nfs/export.go
Fixes: #815
When updates to the NFS mgr API were recently merged on Ceph main branch the go-ceph test started failing. This occurred because go-ceph was unintentionally relying on invalid JSON (an empty string) returned from the API call for an invalid export pseudo path. On ceph main it now returns an empty JSON object. This change treats both empty string and empty JSON object as an error explicitly.
New or infrequent contributors may want to review the go-ceph [Developer's
Guide](https://github.com/ceph/go-ceph/blob/master/docs/development.md)
including the section on how we track [API Status](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status) and the [API Stability …
=> nfs admin: fix handling of non-existing psuedo_paths for export info

README.md
=> README: add v0.20.0 release

cephfs/admin/pin.go, cephfs/admin/pin_test.go, docs/api-status.json, docs/api-status.md
=> cephfs/admin: Add Subvolume{Group} pinning API

docs/api-status.json, docs/api-status.md
Fix the api versions from #851
=> docs: fix version for newest api additions

cephfs/admin/metadata.go, cephfs/admin/metadata_test.go, cephfs/admin/snapshot_metadata.go, cephfs/admin/snapshot_metadata_test.go, cephfs/select_fs.go, cephfs/select_fs_test.go, docs/api-status.json, docs/api-status.md, rbd/migration.go, rbd/migration_test.go, rgw/admin/list_bucket_with_stats.go, rgw/admin/list_bucket_with_stats_test.go
=>  Make preview APIs stable for v0.22

.github/workflows/main.yml
See https://github.com/mxschmitt/action-tmate#manually-triggered-debug
=> CI: add a workflow option for tmate debugging

README.md, cephfs/admin/fs_quiesce.go, cephfs/admin/fs_quiesce_test.go, cephfs/admin/fs_quiesce_unsupported_test.go, docs/api-status.json, docs/api-status.md, docs/release-process.md, rbd/snap_group_namespace.go, rbd/snap_group_namespace_test.go
=> Preparation for release v0.29.0

README.md, docs/api-status.json, docs/api-status.md, rados/rados_getaddrs.go, rados/rados_getaddrs_test.go
=> Release preparation v0.33

cephfs/admin/subvolume_snapshot_path.go, cephfs/admin/subvolume_snapshot_path_test.go, docs/api-status.json, docs/api-status.md
based on https://github.com/ceph/ceph/pull/62708
=> cephfs/admin: Add API to fetch subvolume snapshot path

.github/mergify.yml
ref: [queue_rules](https://docs.mergify.com/configuration/file-format/#queue-rules)
=> github: Fix mergify configuration
