Dockerfile
rbd/rbd.go
rbd/rbd_test.go

add param 'order' to `Create() ` and `Image.Clone()`. `giant` ceph version can on longer be installed through package,  upgrade ci ceph version to `hammer`. Reference to #6 
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

add param 'order' to Create() and Image.Clone()

---

rados/ioctx.go
rados/rados.go
rados/rados_test.go

In Go, the "C" package is a special type of package that creates local symbols
names (non exportable) to the importing package. The result, in the case of
rados.GetRadosError() is that trying to use results in:
cannot use cerr (type C.int) as type rados.C.int in argument to rados.GetRadosError
It seems that "C.int" within 'rados' namespace produces a symbol of the type
`_Ctype_int`, which given it's first character `_` is not exported. As such, we
have the type being defined as `rados._Ctype_int`, which is not accessible
outside of the rados package.
This commit changes the interface to use the native Go `int` type.

Fix rados.GetRadosError() interface to allow package-external use.

---

rados/ioctx.go
rados/rados_test.go

This commit simply adds a SetNamespace() method to IOContext, allowing users to
perform pool operations in the context of a specific namespace.

Namespace support for Pools.

---

rados/ioctx.go
rados/rados_test.go

The current IOContext struct has a ListObjects() method that works well for
pools with a reasonable number of objects. However, for very large pools, having
finer control over the iteration may be desirable.
This commit adds a new Iter() interface for pools. It allows callers to stop
iterating at any time by issuing a iter.Close(). It also allows callers to
"Seek" into the pool list using a token object.

Pool iterator: Implement Iter() interface to allow incremental listing of Pools.

---

rbd/rbd.go
rbd/rbd_test.go

Adds check for `ERANGE`. Fixes https://github.com/ceph/go-ceph/issues/16
Thanks to @neurodrone for tracking down the behavior in librbd.

continue after -ERANGE in retval of rbd_list_children

---

rbd/rbd.go

ReadAt and WriteAt should not rely on image.offset as this prevents the from working in a thread-safe manner.
Hopefully fixes #18

Replace ReadAt and WriteAt with thread-safe versions

---

rbd/rbd.go

Fixes: #21
This fix will also help fixing https://github.com/yp-engineering/rbd-docker-plugin/issues/3, which no need to comment some rbd-plugin's codes to workaround this issue any more.
Signed-off-by: Zhi Zhang <zhangz.david@outlook.com>

Fix rbd list lockers crashing

---

rados/ioctx.go
rados/rados_test.go

This is a rebase of #26. I tested it on production (because who doesn't right?) and the included test passes:
```
=== RUN   TestLocking
--- PASS: TestLocking (1.26s)
PASS
ok      github.com/ceph/go-ceph/rados   1.280s
ceph version 10.2.2 (45107e21c568dd033c2f0a3107dec8f0b0e58374)
```

rados: add support for object locking + test

---

Dockerfile

This moves Go to 1.7.1, using Debian Jessie
Uses Ceph Jewel instead of Hammer
Uses download.ceph.com
Debian Jessie does not have `uuidgen` command by default, so
also needed to install uuid-runtime.
Signed-off-by: Travis Rhoden <trhoden@gmail.com>

Update Dockerfile to Go 1.7.1 and Ceph Jewel

---

rados/rados_test.go

As requested in #32 this adds a test that fails at present.
We attempt to get omap values on an object that does not exist. We would like to get RadosErrorNotFound but instead we get IO Error.

Add test for ENOENT for omap

---

rados/ioctx.go
rados/rados_test.go

The current code generate locks that expires more than 47 years from now...

Fix bogus duration handling in IOContext.Lock*

---

rados/ioctx.go

As mentioned in #42 the deprecation warnings for object list are not really warnings, they error at runtime on luminous.
This PR fixes the functions that error at runtime, but it does leave the deprecation warning for the `rados_read_op_omap_get_vals`. For now, that warning is harmless (it works ok at runtime). 
If the work at [hangzws#2](https://github.com/hangzws/go-ceph/pull/2) is merged, this becomes redundant, but that work also removes support for jewel. As it stands this PR should be safe for jewel.

Get luminous working

---

rados/ioctx.go
rados/rados.go
rados/rados_test.go

RADOS supports listing and iterating over all of the objects in a pool (across namespaces) but at present the go bindings don't explicitly support that. Under the covers this is achieved by passing a magic constant to `rados_ioctx_set_namespace()` so we define that constant for people to use.
Additionally, we can extend the iterator to support returning the namespace of objects if you are iterating across all namespace without breaking the API, so I did that. We unfortunately cannot extend ListObjects without changing the signature, so I omitted that. Anyone needing that info can simply use the iterator interface instead.
I extended the tests of both ListObjects and Iter to check that behavior is correct within and across namespaces.

Improve namespace support

---

rbd/rbd.go

librbd will segfault if attempting to perform snapshot operations on a null `rbd_image_t` parent.

Check that parent image is open before attempting snapshot operations

---

rbd/rbd.go

This simply converts the RBD feature flags to constants (as they should be), and uses Go's iota helper for enum-like constants.

Convert RBD feature flags to constants with iota

---

rbd/rbd.go
rbd/rbd_test.go

Simple wrappers around Ceph's RBD trash functionality. Refs #62.

Implement wrappers around rbd_trash_* functions

---

.travis.yml
Dockerfile
Makefile
README.md
cephfs/cephfs.go
cephfs/cephfs_test.go
micro-osd.sh

This commit adds the following cephfs functions:
* Unmount // Unmounting is necessary to cleanup mounts
* Release // Release destroys the cmount ~ end of transaction
* RemoveDir // inverse of MakeDir
* Chown // change ownership of file or directory
* Chmod // change permissions of file or directory
Tests are included for each function.
In addition to these changes modifications to:
.travis.yml, Dockerfile, and Makefile
were made to accomodate tests to mount the ceph volume.  Tests use
fuse to mount the volume which requires adding:
--device /dev/fuse --cap-add SYS_ADMIN --security-opt \
apparmor:unconfined
to the docker container (alternatively --privileged works but adds
additional permissions).
Changes to README add the above docker changes as well as point
users to the necessary ceph …

cephfs: add unmount, release, chmod, chown, etc 

---

rados/ioctx.go

Signed-off-by: zhangyue <zy675793960@yeah.net>
fix both #76 and #79

bugfix: fix rados_read_op_omap_get_vals deprecated

---

Makefile

Add new variables to the Makefile that allow the use of other container
runtimes (that have a docker compatible cli) and allow setting extra
opts to work on platforms that don't run apparmor.
All defaults continue to be the same as before.

makefile: support using other container runtimes

---

Dockerfile
Makefile

This PR fixes two issues where `make test-docker` does not work on my system:
1. blocked waiting for input while enabling ppa:gophers/archive repository
2. failure with `go get` dependencies

Improve 'make test-docker'

---

Makefile

Fedora based distributions don't use AppArmor but SELinux instead.
This change detects the distribution and sets the --security-opts
accordingly.

Makefile: Fix CONTAINER_OPTS for Fedora

---

Dockerfile
entrypoint.sh

Adds cli parsing to the entrypoint script allowing for:
1. Custom path to micro-osd script
This allows easier testing of the script itself or quick
and dirty customization for special one-off tests
2. Selecting tests to run (or "ALL" or "NONE")
This allows the user to run only a subset of the tests as needed.
3. Option to pause indefinitely after tests complete
This keeps the containerized environment alive after tests
have run for debugging or just for creating a quick and dirty
ceph environment for playing around.

enhance test container entrypoint script behavior

---

cephfs/cephfs_test.go
rbd/rbd_test.go

This change replaces a couple of functions from the "assert" package
with the corresponding functions from the "require", where the
following code relies on a non-nil object.

Tests: avoid segmentation faults in tests

---

rbd/rbd_test.go

Previously, the tests were shelling out to run 'uuidgen' which
is not particularly efficient and a bit ugly. Switch this test
to use the same uuid library already in use by the rados test code.

rbd: use uuid library, rather than shelling out, in rbd test

---

rbd/rbd.go
rbd/rbd_test.go

The C library offers rbd_create2() and rbd_create3() and does not try to
cover all options with rbd_create(). For users that are familiar with
the C API, the Create2() and Create3() functions have been added.
The existing Create() API still handles the complete set of
rbd_create*() functions, so backwards compatibility is covered.
**Note:** `Create4()` is added with #111 
<hr/>
If this is accepted, adding the other variations for `Clone*()` and so on would be needed too. This can be done in addition PRs, or I can extend this one.

rbd: split Create() off into Create2() ad Create3() following librbd.h

---

Dockerfile
rbd/options.go
rbd/options_test.go
rbd/rbd.go
rbd/rbd_test.go

While rewriting Ceph-CSI to use  go-ceph instead of the `rbd` command, some functionality is missing in go-ceph. One of the missing pieces is support for setting certain options while creating an image (optional data-pool).
This series adds support for `rbd_image_options_t` with getter/setter functions and the like based on `librbd.h`.
Note that Mimic added a new option, hence updating the tests to consume a more recent version (Nautilus, was Luminous).
~~In order to keep this working with Luminous, `rbd/rbd_options_list.pgo` is used to generate `rbd/rbd_options_list.go` which may, or may not include `RBD_IMAGE_OPTION_FLATTEN`, depending on the Ceph version.~~ (Does not work as expected)
As Travis CI has been configured to run on Luminous, `RBD_IMAGE_OPTION_FLATTEN` has been disabled and …

Add support for rbd_image_options_t

---

rbd/rbd.go
rbd/rbd_test.go

Make it possible to easily validate the *Image and *Snapshot objects
before using them. This makes the use of go-ceph for RBD functions more
stable, and it is less likely that incorrect use causes Go panics.

rbd: improve error checking

---

rados/conn.go
rados/ioctx.go

Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

.revive.toml
.travis.yml
Makefile

Unlike the rather strict golint tool the [revive](https://github.com/mgechev/revive) tool is configurable and will allow us to incrementally improve things and/or leave suboptimal items in place for backwards compatibility. This initial pr adds configuration for revive and uses it in the Travis CI config and Makefile.

[RFC] Use the revive checker for style checks

---

rados/doc.go
rbd/doc.go

The rbd and rados packages had doc.go files with only packages but the doc comment was not formatted in the standard manner. Change them to the standard style.

Fix package comments for doc.go files

---

rbd/rbd.go
rbd/rbd_test.go

Translate the return value (errno) from the C rbd_*() functions into the
standardized strerror() error message.

rbd: return more useful error messages

---

.github/pull_request_template.md

Template provides brief reminders on what the project expects on
all prs. Some of the boilerplate I borrowed from ceph/ceph's template other parts are just what's been frequently requested in existing PRs.

github: configure a pull request template

---

rados/conn.go
rados/rados_test.go

To query PG we need to send PG command via [rados C API](https://github.com/ceph/ceph/blob/mimic/src/include/rados/librados.h#L3850-L3854). However this is presently not implemented by `rados.go`. This PR adds support for sending `PGCommand` that is useful for querying information for a specific PG.

rados: add support for sending PG commands

---

rbd/rbd.go

By convention many projects are separating the golang stdlib imports
from other imports. Do that as well for rbd.go.

rbd: separate standard lib imports from pkg imports

---

rbd/rbd.go
rbd/rbd_test.go

A recent PR added new error values that were similar to the existing
naming convention but were not the normal go convention. Change all the
errors to match typical convention but leave the older names as aliases
such that older code will continue to work (for now).

rbd: use conventional naming style for errors

---

rbd/rbd.go
rbd/rbd_test.go

With these changes the test coverage of `rbd/rbd.go` increases to 69.3% (from 59.3% on current master, hence the edits of this message).
Minor improvements might have sneaked in (constants for `Image.Seek()` `whence` values), and improvements for `Image.Discard()` as mentioned in #123.

Increase test coverage for RBD package

---

cephfs/cephfs.go
cephfs/cephfs_test.go
entrypoint.sh
errutil/strerror.go
errutil/strerror_test.go
rados/rados.go
rados/rados_test.go
rbd/rbd.go
rbd/rbd_test.go

This series is insipred by #120 and refactors the changes there to use a common approach across all sub packages in the library. It incidentally also tries to clean up some of the disparate error handling approaches across the packages.
This PR is current do-not-merge because, due to mistakes and laziness it currently incorporates changes from other PRs. Please take a look at those first (PRs #130 and #131 IIRC) and I'll rebase when the time is right. This PR partially exists as a preview and so that I don't just sit on the work. :-)
Feel free to be harsh with the naming of the error handling utility functions and package that I added.

Make error handling more common 

---

.revive.toml

Previously, revive was configured to only warn on detected issues.  We
have eliminated all those issues and so can set revive to error out and
thus the 'make check' rule will fail if new issues are introduced.
Also, enable exported vars check at the warning (non-failing) level.

Enable stricter checking by default

---

cephfs/cephfs_test.go
rados/rados_test.go
rbd/rbd_test.go

Initially, I was only working on reducing the test-setup boilerplate in rbd_test.go. However, while testing the error handling I added to the common conn setup function I noted that the test suite would block forever.
Thus for both rbd and rados I also changed it so that the tests only wait 5 seconds to connect. I looked for a native timeout in ceph but did not find one, and derived this approach from the code of 'ceph.in' (python code that generates the ceph cli command).
The cephfs stuff is set up slightly differently but now also is handled in a similar fashion where appropriate.

Improve test setup and connect behavior

---

.gitignore
entrypoint.sh

Run the tests for each sub-package as a separate invocation.
Make the package selectable.
This has a few small advantages:
* When iterating on a single package the other packages do not run
* Better coverage summary line printed after each test
* Slightly better output with verbose test output

entrypoint: handle the sub-packages separately

---

contrib/apicompare.py

This fairly hacky script can be used to check how much of the
various apis are covered by the go-ceph library.
It doesn't care about a lot of subtlety at the moment but does
give a fair idea of what types of functions are implemented vs.
those that are not.
Requires the tool 'castxml'.

contrib: create a hacky script for comparing api coverage

---

Makefile

No need to compile the files under the contrib/ directory.
Currently, running 'make' does not do anything useful.

build: compile all go files with "make"

---

rbd/rbd.go

This PR includes change from PR #137 (to help find invalid doc comments / prove we're making progress). Please review that PR first.
Currently, the rbd package is the "messiest" with copy-n-pastes of the c function prototype as many of the doc comments. Instead I went with the following formats:
```golang
// FuncName does something.
func FuncName() {
}
```
For code that does not act as a wrapper around a C function, didn't need a reference to a c function or simply doesn't need the extra detail.
and
```golang
// FuncName does something.
//
// Implements:
//  int rbd_foo_bar(int i, uint64_t bloop);
func FuncName(i int, bloop uint64) {
}
```
For code that references a particular function from the c api. I removed unused / invalid references if they existed.
This has the nice side-effect of …

Improve doc comment style/approach

---

rbd/options.go

Add documentation to the functions in the rbd/options.go file.
See-also: #138

rbd: improve doc comments for RbdImageOptions functions

---

rbd/rbd.go
rbd/rbd_test.go

It seems that `WriteAt()` and `ReadAt()` did not have any test cases.
`ReadAt()` should return the number of bytes that have been read. In case the number of bytes is fewer than the number of bytes requested, `io.EOF` is returned. **This was not the case, and this PR contains a bugfix for that.**

rbd: Add tests for Image.WriteAt() and Image.ReadAt()

---

rbd/rbd.go
rbd/rbd_test.go

Similar to the problem found in `ReadAt()` (#154), `Read()` does not return `io.EOF` on a short read.

Fix Read() to return io.EOF on short read

---

go.mod
go.sum

Establish a go.mod (and go.sum) file such that this library can be
handled as a Go module. This has the added benefit of now being
useful outside of gopath.
I do not believe we need to release to provide/use module support but
we should possibly start considering creating v0 tags soonish.
See also: https://blog.golang.org/publishing-go-modules
Closes: #70

go-ceph: publish library as a go module

---

cephfs/cephfs.go
cephfs/cephfs_test.go
rados/conn.go

These changes wrap the rados and cephfs apis needed to use an existing rados connection to establish a cephfs mount.

cephfs: Support creating mount from an existing rados connection

---

doc.go

go-ceph: fix typo in doc.go

---

cephfs/cephfs.go
cephfs/cephfs_test.go

The ceph api function supports passing a string to identify the
client doing the mount. Expose that aspect of the api with a
new function CreateMountWithId.
Follow up PRs that add wrappers for mds command functions and more extensive verification of the feature to follow.

cephfs: allow creating mount with an id

---

cephfs/doc.go
errutil/strerror.go

Add doc comments for errutil and cephfs which were lacking top-level doc comments.

add doc comments for all sub-packages with exported funcs

---

rados/ioctx.go
rados/rados.go
rados/rados_test.go

Ceph-CSI creates new objects without initial data. This is a functionality that is missing in go-ceph at the moment.

rados: add Create() function to create new objects

---

Dockerfile
entrypoint.sh

When building the container image for running tests take the older of
the two current releases from Go upstream. We use the older version
in order to make sure we are testing with something supported but maybe
not everyone is on 1.13 yet.
This also enables the use of go modules to ensure we get the proper
versions of dependencies.
Fixes: #166

testing: use Go 1.12 from go upstream in ci container

---

rbd/rbd.go
rbd/rbd_test.go

First off I am adding two new functions that map to librbd's rbd_open and rbd_open_read_only, currently named OpenImage and OpenImageReadOnly. These return new Image instances.
The Create4 function is renamed to CreateImage and I hope to have that be the canonical way to create an image in the future.
A new standalone RemoveImage function is added that more closely maps to the underlying ceph apis. The current Remove function is re-implemented to use RemoveImage.
The current Open method is marked deprecated. I plan on retaining the Open method for at least one release [1] and then removing it. I think we should do this because I expect Open to be a very commonly used function. 
I would like to see some of the other PRs that clean up the comments and test code merged prior to this one so I …

rbd: update rbd open, create and remove image functions

---

rbd/rbd.go
rbd/rbd_test.go

Add GetId wrapper for rbd_get_id.
Add OpenImageById and OpenImageByIdReadOnly wrappers for rbd_open_by_id and rbd_open_by_id_read_only.
Add tests for all. Coverage of these tests is a tad spotty as it currently seems impossible to test the buffer-too-small case in GetId as we're going to have small ids. In addition, ceph libs crash when asked to open an image by an invalid id so trivially testing the error handling is currently not possible. The tests exist but are set to always skip until we know a ceph version fixes this issue and then we will need to detect it to enable the tests.

rbd: add functions to open image by id

---

Makefile

The go test command's -c switch builds the test binary but does not
execute it. It is convenient to do quick compile checks of the libraries
and test code at once without having to bring up the ceph instance in
the test container. This change allows one to run 'make test-bins' or
'make rbd.test' to compile but not run the test & library code.

makefile: add targets for test binaries

---

.travis.yml
Dockerfile
Makefile
README.md
entrypoint.sh
rbd/rbd.go
rbd/rbd_mimic.go
rbd/rbd_nautilus.go
rbd/snapshot_mimic.go
rbd/snapshot_nautilus.go

The following warnings about using deprecated functions are being resolved with this PR:
```
cgo-gcc-prolog: In function '_cgo_8f906ca4e7ab_Cfunc_rbd_get_parent_info':
cgo-gcc-prolog:349:2: warning: 'rbd_get_parent_info' is deprecated [-Wdeprecated-declarations]
In file included from $WORK/b128/rbd.cover.go:10:0:
/usr/include/rbd/librbd.h:571:18: note: declared here
CEPH_RBD_API int rbd_get_parent_info(rbd_image_t image,
^
cgo-gcc-prolog: In function '_cgo_8f906ca4e7ab_Cfunc_rbd_list':
cgo-gcc-prolog:426:2: warning: 'rbd_list' is deprecated [-Wdeprecated-declarations]
In file included from $WORK/b128/rbd.cover.go:10:0:
/usr/include/rbd/librbd.h:330:18: note: declared here
CEPH_RBD_API int rbd_list(rados_ioctx_t io, char *names, size_t *size)
^
cgo-gcc-prolog: In function …
```

rbd: remove usage of deprecated functions

---

README.md

The older godoc.org encourages the user to use pkg.go.dev instead.
Change our link to point directly there (and use https).

readme: update doc link to pkg.go.dev

---

docs/release-process.md

Add a simple document outlining the current release process. It's pretty minimal but I'm forgetful and don't want to reinvent the wheel next time.

docs: document the release process

---

cephfs/cephfs.go
cephfs/cephfs_test.go
cephfs/conn_nautilus.go
cephfs/conn_nautilus_test.go

NOTE: This is based on the patches in PR #182. Please review/merge that first.
The existing Mount() method did not provide a way to access the root
path argument to ceph_mount. This new function allows the caller to
specify an alternate root dir for the mount.

cephfs: add MountWithRoot to implement the root arg to ceph_mount

---

rbd/features.go
rbd/features_mimic.go
rbd/features_mimic_test.go
rbd/features_nautilus.go
rbd/features_nautilus_test.go
rbd/features_test.go
rbd/rbd.go
rbd/rbd_test.go

Split the features from `rbd/rbd.go` into its own file. This makes is easier to extend the functionality of feature-bits.
Mimic and Nautilus added more features, so these constants need to be compiled-in on selective base (using build-tags as is done for other things already).
Some features allow being modified after image creation. Support for `rbd_update_features()` has been added for this now too, though `Image.UpdateFeatures()`.
Closes: #183

Add support for all RBD image-features up to including Nautilus

---

rbd/watchers_mimic.go
rbd/watchers_mimic_test.go

Checking if there are other clients interested in changes to an RBD
image is important for certain actions. For example, the Ceph-CSI
project would not want to remove an image in case it is still mounted
somewhere.
Listing the details of the watchers is not important at the moment.
Adding a watcher is only implemented for testing, and is not functional
enough to get notifications through a callback. This is something that
needs more investigation and can be added at a later point.

rbd: add support for listing watchers on an RBD image

---

entrypoint.sh
internal/callbacks/callbacks.go
internal/callbacks/callbacks_test.go
rbd/callback_shims.go
rbd/diff_iterate.go
rbd/diff_iterate_test.go

Add a DiffIterate wrapper for rbd_diff_iterate2.
First patch adds a helper type that deals with some of the tricky aspects of callbacks between C and Go. See the commit description and code comments for references about why this is needed and the implementation.
The 2nd patch actually implements the callback wrappers needed to make the call and the wrapper around the librbd function itself. We only wrap rbd_diff_iterate2 as, unless I'm wrong, it fully supersedes rbd_diff_iterate when the parameters are defaulted.
I opted to put all of the arguments to rbd_diff_iterate2 in the DiffIterateConfig as I find more then 4-5 arguments to a function call in Go start to get confusing. Because of this choice I had the ability to pass the whole configuration value to the callback. I did so, but this …

rbd: create DiffIterate wrapper function

---

rbd/rbd.go
rbd/rbd_test.go
rbd/snapshot.go
rbd/snapshot_test.go

No functionality change.
First commit just moves the functions and types.
Second commit adds missing doc comments for many of the items in the new file.

rbd: move snapshot related functionality to a new file

---

cephfs/cephfs.go
cephfs/cephfs_test.go

These are implemented similarly to the rados equivalents.
I'm putting a todo on myself to look into dealing with the ENAMETOOLONG case that existed in rados code and exists here now.

cephfs: add SetConfigOption and GetConfigOption functions

---

entrypoint.sh

This can be useful when running the script outside of the
container or doing other sneaky things. :-)

entrypoint: add a --results option for alternate results dir

---

entrypoint.sh
rados/ioctx.go
rbd/diff_iterate.go
rbd/rbd.go
rbd/rbd_mimic.go
rbd/rbd_nautilus.go

These changes first fix some outstanding issues with go vet, all of which pertain to converting from a uintptr type to an unsafe.Pointer / pointer. While I don't 100% understand why its bad enough to warn with go vet but not break the compile :-)
I would rather get go vet working to prevent future issues like a similar conversion in the newly added diff_iterate support. A helper function is added to rbd to aid with any future functions and to avoid having to mess with a lot of calls if we have to tweak this again.
Finally, we enable go vet in the `entrypoint.sh` script on a per-package basis. It is run prior to the go tests but will still run the tests even in vet fails (either failing will fail the overall script).

Fix "go vet" errors and then enable vet in tests

---

rbd/rbd.go

Doc comment improvements in rbd to get us a tad bit closer to enabling more checks from revive as failures rather than warnings.

rbd: small fixes to pass static checks

---

cephfs/cephfs.go
rados/rados.go
rbd/rbd.go

Until we (me I suppose) come up with a better approach to the errors in general, I prefer disabling the "stuttering" check for exported items in revive in the code. This gets us closer to changing the check from a warning to an error and not adding any new cases of "stuttering" to the code base.

Disable checks for error types with "stuttering" prefixes

---

entrypoint.sh

This further improves the ability to use the script outside the
container itself and against alternate ceph cluster configs.

entrypoint: allow configuring ceph config source

---

rbd/rbd.go

Assorted doc comments on functions to reduce the number of warnings produced by revive code checker tool. This continues to get us closer to making this category of checks errors rather than warnings.

rbd: add doc comments to cut down on revive warnings

---

.travis.yml

Within the last 24hrs the "octopus" release of ceph is available, and
matching tags have been created in the ceph containers project. Consume
the release name rather than master.
Fixes: #197

travis: use "octopus" release by name

---

cephfs/cephfs.go
cephfs/cephfs_test.go
cephfs/errors.go
cephfs/errors_test.go
rados/conn.go
rados/errors.go
rados/errors_test.go
rados/ioctx.go
rados/object_iter.go
rados/omap.go
rados/rados.go
rados/rados_test.go
rbd/errors.go
rbd/errors_test.go
rbd/rbd.go
rbd/rbd_test.go

Move errors and error types and error functions into a per-package "errors.go" file, for rados, rbd, and cephfs.
Clean up and make the usage more consistent across the 3 packages.

Unify error handling a bit more

---

README.md

Use the readme to "advertise" that the team plans to be regularly available online during two time slots per week, one "early" and one "late" slot.

readme: advertise "office hours"

---

cephfs/directory.go
cephfs/directory_test.go

This PR conflicts with / obsoletes PR #91.
Start implementing functions related to directories in cephfs. We establish a new directory handle type with associated open and close functions. We add a readdir wrapper. We add a rewinddir wrapper and with readdir create a List convenience function for common use cases that just want to consume all the dir entries in one call and iterate over them. The List function returns a DirEntries type that has a Names() method that returns only the names of the directory entries, once again as a convenience for the common case.

cephfs: Initial directory support

---

.revive.toml
package_test.go
rados/rados_test.go
rbd/errors.go
rbd/rbd_test.go

I scanned through some of the other revive rules we weren't using and, after fixing issues found by the tool, enabled these rules in the configuration. I think these rules should be fairly uncontroversial. Nearly all of the issues found and fixed were in the test code.

Enable additional revive checks

---

cephfs/cephfs.go
cephfs/cephfs_test.go
cephfs/mount_perms_mimic.go
cephfs/mount_perms_mimic_test.go
cephfs/userperm.go
cephfs/userperm_test.go

Continuing recent work around making tests in cephfs more flexible the following patches fix another lack of idempotence in tests. It also adds new functions wraping libcephfs apis needed to manage UserPerm(s) and set them prior to mounting the fs.
Fixes #205.

cephfs: add functionality needed to specify mount user creds

---

.github/workflows/main.yml
Makefile

Make use of the github workflows archive feature to capture the coverage report(s) that are generated when the CI test container runs.
The results dir is currently defaulted to the empty string so there should be no change to the developers workflow. However, if you want to save the results locally you can now set RESULTS_DIR. For example: `make test-container RESULTS_DIR="$PWD/_results"`

Archive html coverage reports generated during ci jobs

---

cephfs/errors.go
cephfs/file.go
cephfs/file_test.go
cephfs/path.go

Add cephfs functions related to regular files including:
* open
* close
* read
* write
* seek
Additionally, we add unlink to the paths.go file so that the files tests can clean up after themselves.

cephfs: add file open/close and read/write/seek and unlink

---

cephfs/directory.go
cephfs/directory_test.go

CephFS returns Linux-style struct dirent that has a d_type field.
It appears to properly make use of the field. This change exposes
the field using a DType type and associated constants as well
as a DType() function for the DirEntry.
Fixes #233

cephfs: add DType type and getter function for directory entries

---

cephfs/path.go
cephfs/path_test.go

Link function implements ceph_link().
Symlink function implements ceph_symlink().
Readlink function implements ceph_readlink().
To fix https://github.com/ceph/go-ceph/issues/218

cephfs: adding Link, Symlink and Readlink functions

---

cephfs/cephfs.go
cephfs/cephfs_test.go
cephfs/path.go

ceph MountInfo pointer is being passed in the functions without a validation check, if it is nil there may be a crash. Fixed the functions to first validate mount.mount

cephfs: Validate mount.mount usage in cephfs/path.go

---

cephfs/file.go
cephfs/file_test.go

Fchmod() implemenets ceph_fchmod()
Fchown() implements ceph_fchown()
To fix: https://github.com/ceph/go-ceph/issues/240

cephfs: implement wrappers for fchmod and fchown

---

cephfs/errors.go
cephfs/path.go
cephfs/path_test.go
cephfs/statx.go
cephfs/statx_test.go
cephfs/timespec.go
go.mod
go.sum

Add a Statx wrapper for ceph_statx. Add a type wrapping the statx status
info that exposes the various fields from the C-struct. Note that the
ceph struct is not the same as the linux statx struct.
A wrapper around x/sys's unix.Timspec has been added and used for the time fields.
The fields in the Go struct are now public. Gone are the accessor functions.  The idea is that future ceph functionality will make use of a "writable" CephStatx structure. C structs are converted/copied into the Golang struct.
We will not be wrapping ceph_{f,l,}stat functions. We may choose to make higher level interfaces on top of these, probably hewing closer to the Go os module higher-level abstractions. This is all outside the scope of the PR.

cephfs: add path based Statx function implmenting ceph_statx

---

Makefile
cephfs/command.go
entrypoint.sh
internal/cutil/command_input.go
internal/cutil/command_input_test.go
internal/cutil/command_output.go
internal/cutil/command_output_test.go
internal/cutil/type_aliases.go
rados/command.go

Why we may want to do this:
The various *Command and *CommandWithInputBuffer functions all behave similarly but we are effectively copy-n-pasting the argument and result processing over and over. These changes establish a new `cutil` internal package to help with this and other future c-and-go conversions that are common. It makes two new types one for handling the input, and one for the output. Then we convert the functions in rados and cephfs.
Why we may not want to do this:
Go's cgo support is pretty nice when used entirely within one package but the current design of go/cgo is pretty hostile to allowing cgo details to transition across packages. You can not use the cgo types directly and thus have to resort to workarounds, like overuse (abuse?) of unsafe.Pointer.
As this is an …

refactor command funcs arguments set up

---

.gitignore

The .test files are generated by some makefile rules and should
never be checked in.
There's also no reason to track json files which may be generated
by running tools.

gitignore: ignore .test and .json files

---

cephfs/file_test.go

The tests for Fchown and Fchmod were not checking the cases where the file object was not valid. Tis is a quick-n-dirty add of those checks.

cephfs: add missing coverage in file validate cases

---

Makefile

Previously, "make check" only ran revive and its static checks.  The
entrypoint.sh script ran a formatting check *after* setting up ceph.
Now, "make check" runs both revive and gofmt. New make rules
check-revive and check-format run the individual tools respectively.
This is done to quicken the feedback in both the CI and locally for
formatting mistakes. Users can now easily run `make check
test-container` and avoid a long wait to set up ceph just to find out
there was a silly formatting error present.

makefile: include formatting as part of "make check"

---

.gitignore
Makefile
contrib/implements/README.md
contrib/implements/internal/implements/cast.go
contrib/implements/internal/implements/cfunctions.go
contrib/implements/internal/implements/gosrc.go
contrib/implements/internal/implements/inspector.go
contrib/implements/internal/implements/json_report.go
contrib/implements/internal/implements/log.go
contrib/implements/internal/implements/report.go
contrib/implements/main.go

Add a new Go-based tool to the contrib dir that helps determine what is covered, what is missing, and other basic stats.
This should be a superset of the features of `apicompare.py` in the contrib dir. I converted it to Go to make the languages for the library and the tool consistent and perhaps easier for others to contribute to. In addition we can now make use of the native Go AST packages.
If this is accepted I will probably file a follow up PR to remove the python based apicompare.py.
Future directions:
* I want to run the tool in the CI runs with the tests and capture the output
* I hope to make use of the json output to do additional analysis per-pr, like maybe reporting on
* Adding code to verify that the "Implements:" comment standard is formatted properly in the CI.
* Adding the …

Add an "implements" tool to contrib

---

cephfs/directory.go
cephfs/directory_test.go

Add the ReadDirPlus function call, wrapping ceph_readdirplus_r. Add
DirEntryPlus which is a DirEntry plus a getter for the statx field.
Add a test similar to the ReadDir test and (since it is possible to
induce an error with ceph_readdirplus_r) a test for the error handling
path to improve code coverage.
Fixes: #260

cephfs: add ReadDirPlus function and associated types

---

cephfs/file.go
cephfs/file_test.go

Use the CephStatx type previously added to the library to implement a
wrapper for the ceph_fstatx function.
Fixes: #283

cephfs: add Fstatx function to file type

---

cephfs/file.go
cephfs/file_test.go

Added ceph_fallocate() which  preallocates or releases disk space
for the file for the given byte range.
Fixes: https://github.com/ceph/go-ceph/issues/246

cephfs: add ceph_fallocate() function

---

rados/command.go
rados/command_test.go

This series of changes do a little clean up before wrapping rados_osd_command & rados_mon_command_target and tests.
Fixes: #272 
Fixes: #270

rados: add support for remaining missing "command" funcs

---

rbd/errors.go
rbd/rbd.go
rbd/rbd_test.go

Trying to remove an opened read-write image results in an error `Device or resource busy`. This change adds an additional validation case in the `Remove()` method and returns more understandable error.

rbd: add better error when attempting to remove opened images

---

.github/workflows/main.yml
contrib/implements/internal/implements/report.go
contrib/implements/main.go
entrypoint.sh
testing/containers/ceph/Dockerfile

This series enhances the implements tool to produce multiple kinds of output in one run of the tool rather than having to run it multiple times.
Then the container and entrypoint script are updated to run the tool after the code coverage report is generated. Unfortunately, getting castxml on the centos7 based containers seems like an inordinate amount of work so I skipped that for now. Only the centos8 (octopus) based container will run the tool.
In the spirit of something-is-better-than-nothing the octopus builds are a good enough starting point.
When all the conditions should be met the json and test output of the implements report files are to be captured by the github workflow.

Improve and begin integrating 'implements'-tool reporting automation

---

rbd/options.go
rbd/options_mimic.go
rbd/options_nautilus.go
rbd/options_octopus.go

Recent Ceph versions add more RbdImageOption constants, these were missing in go-ceph.
Closes: #295

Add RbdImageOption constants for Ceph versions including Octopus

---

rbd/rbd.go
rbd/rbd_test.go

When passing `nil` arguments or empty strings for names some librbd functions may segfault. We do not like this, so we catch the errors early and return something to the called.
Reported-by: @madhu-1

rbd: additional error checking in OpenImage, CreateImage and RemoveImage

---

cephfs/file.go
cephfs/file_test.go

Add wrappers for ceph_fsync. The Fsync call directly wraps ceph_fsync
which provides options to behave more like fsync or more like fdatasync.
Add Sync, a simpler wrapper over Fsync, to match any interfaces that
make use of `File.Sync` from Go's os package.
Fixes: #250 
The tests here are a little on the weak side because we don't really do the extra heavy lifting to verify the flags do what they say on tin, but I trust this part of ceph to work and our wrapper is pretty trivial.

cephfs: add Fsync and Sync calls for open files

---

rbd/pool_nautilus.go
rbd/pool_nautilus_test.go

added a check to validate ioctx in all the three *PoolMetadata() functions namely
GetPoolMetadata, SetPoolMetadata and RemovePoolMetadata

rbd: additional error checking in *PoolMetadata() functions

---

rbd/errors.go
rbd/namespace_nautilus.go
rbd/namespace_nautilus_test.go

Added wrappers for following four functions:
1. rbd_namespace_create()
2. rbd_namespace_remove()
3. rbd_namespace_exists()
4. rbd_namespace_list()
Fixes: https://github.com/ceph/go-ceph/issues/276

rbd: add wrappers for rbd_namespace_* functions

---

Makefile

When working locally I was finding it annoying to have to remove the "build marker" just to switch between images based on nautilus, octopus, etc. when testing features that vary by ceph version.
This did not impact the ci because it creates a separate (vm) instance for each run.
Now, the build markers are per- ceph version.
I also made it so the makefile would auto-detect if you have docker vs. podman, similar to, but not the same as the way ceph-csi was doing it.
I removed some trailing whitespace that just looked ugly in my editor. :-)
We now pass `-tags $(CEPH_VERSON)` on the make rules that invoke go test, as we missed that before but because I have nautilus locally I hadn't noticed it until the first octopus only files were added recently.

Minor makefile workflow improvements

---

cephfs/statx.go
internal/timespec/timespec.go
rbd/rbd.go
rbd/rbd_nautilus.go
rbd/rbd_nautilus_test.go

Ceph-CSI needs functions to fetch the timestamps from RBD images, these functions have not been implemented in go-ceph/rbd yet.
CephFS already returns a `Timespec` type, which is `golang.org/x/sys/unix.Timespec` compatible. Re-using that in thr rbd package with `cephfs.Timespec` is a little ugly, so the 'proxy type' has been moved under `internal/timespec` package. This might be a little controversial, but I could not think of a different way without duplicating the code too much. This approach does not require the consumers of go-ceph/cephfs to make any changes.
Closes: #309

Add support for rbd_get_{create,access,modify}_timestamp() functions

---

testing/containers/ceph/Dockerfile

On octopus taking in the -devel packages causes *some* of the packages
to be updated but not all. This apparently makes ceph-fuse fail to
start correctly by blocking forever. This works around that issue.
fixes: #323

testing: update container packages before installing new ones

---

cephfs/errors.go
rados/conn.go
rados/errors.go
rados/ioctx.go
rbd/diff_iterate.go
rbd/diff_iterate_test.go
rbd/errors.go
rbd/features.go
rbd/rbd.go
rbd/rbd_nautilus_test.go
rbd/snapshot.go
rbd/snapshot_mimic.go
rbd/snapshot_nautilus.go

In order to avoid external dependencies on implementation details, this change replaces the error types with the unexported versions. In case some application really needs access to the integer value, it can use the pattern
```
var intErr interface{ Int() int }
if errors.As(err, intErr) { ... intErr.Int() ... }
```

Make error types unexported

---

cephfs/statfs.go
cephfs/statfs_test.go

Implement a wrapper function and data type for ceph_statfs. It's actually pretty useless as a high number of the fields are not filled in with useful values by ceph. When they do, we'll get 'em too.
Fixes: #263

cephfs: add StatFS implementing ceph_statfs

---

rbd/callback_shims_mimic.go
rbd/watchers_mimic.go
rbd/watchers_mimic_test.go

These patches add support for setting watches on rbd images via a new UpdateWatch function implementing rbd_update_watch as well as Unwatch implementing rbd_update_unwatch, to remove the watch. Tests are included, along with an extensive test case using watch callbacks to feed a go channel. This test exercises multiples watches at once as well as interaction between C and Go code.

rbd: Add UpdateWatch, Unwatch, and rbd metadata change watch callback support

---

internal/cutil/splitbuf.go
internal/cutil/splitbuf_test.go
rados/conn.go
rbd/namespace_nautilus.go
rbd/rbd.go
rbd/rbd_mimic.go
rbd/snapshot_mimic.go

There's a recurring pattern in some of the Ceph APIs where a single large buffer & length is passed to the function and the call fills that buffer with one or more C-strings. There was one helper function in rbd for this as well as a bunch of copy and pastes of a similar approach.
One instance of this pattern was recently merged and another one that I am working on is on deck.
These changes add SplitBuffer and SplitSparseBuffer functions for extracting a list     of strings from a single buffer, typically returned in C code, from     a single Go buffer. The SplitBuffer variant will return empty strings    if multiple nulls are found in sequence, assuming that the C code
packs data between on single null byte (expect the final byte).     The SplitSparseBuffer variant assumes that the C …

Create common utilty functions for splitting C buffers

---

cephfs/cephfs.go
cephfs/cephfs_test.go
cephfs/errors.go
rados/conn.go
rados/errors.go
rados/rados_test.go

While looking at implementing the functions needed for cephfs I looked at the similar functions in rados. Seeing the "placeholder" thing with fresh eyes annoyed me enough that I split the function into a direct wrap of the ceph call and a higher level call for backwards compat with the previous ParseCmdLineArgs function. I also improved a doc comment.
Then using the rados functions as a guide I added ParseConfigArgv and ParseDefaultConfigEnv to cephfs.
Fixes: #245

cephfs: add functions to parse argv and env

---

rados/ioctx.go
rados/rados_test.go

The GetLastVersion returns a number representing the most recent
read/write version for the io context.
This will become more useful later on when more write op and read op functions are implemented.

rados: add GetLastVersion implementing rados_get_last_version

---

rados/errors.go
rados/ioctx.go
rados/snapshot.go
rados/snapshot_test.go

Implemented following rados API components:
- rados_ioctx_snap_create
- rados_ioctx_snap_get_name
- rados_ioctx_snap_get_stamp
- rados_ioctx_snap_list
- rados_ioctx_snap_lookup
- rados_ioctx_snap_remove
- rados_ioctx_snap_rollback
- rados_ioctx_snap_set_read
Fixes: #269

rados: implement rados pool snapshot functionality

---

rbd/rbd.go

Corresponding fields for Parent_pool and Parent_name have been deprecated from
ceph's rbd_image_info_t stuct, removing the same from go-ceph's ImageInfo struct.
Fixes: #312

rbd: remove deprecated fields from ImageInfo struct

---

Makefile
micro-osd.sh

This PR adds micro-osd.sh to the dependency list to the container build Makefile target, and disables the check for available free disk space, which in container context on a laptop can easily drop below 5%.

Some micro-osd.sh related cleanup

---

cephfs/file_xattr.go
cephfs/file_xattr_test.go
cephfs/path_xattr.go
cephfs/path_xattr_test.go

Add functions needed to read/write/etc xattrs from paths. Both "regular" and "l-prefix" functions are present.
The spelling/case of the"l-prefix" functions are based on the naming approach in Go's os package which uses "Lstat" or "Lchown" rather than "LChown" so here we use "LsetXattr" rather than "LSetXattr" for example.
Fixes: #255

cephfs: add path-based xattr functions

---

cephfs/errors.go
cephfs/errors_test.go
internal/errutil/strerror.go
internal/errutil/strerror_test.go
rados/errors.go
rados/errors_test.go
rbd/diff_iterate_test.go
rbd/errors.go
rbd/errors_test.go

Fixes: #343 
These changes change the function that was formerly called `Errno` to `ErrorCode`.
For consistency with the above we now use a common formatting function for the three package error types and it prints negative numbers when the error code is negative (as it should typically be).
See linked issue for more context.

General changes to error types

---

testing/containers/ceph/Dockerfile

Now that ceph/daemon-base:latest-octopus is on v15.2.4 we can
stop the need to update already installed packages in the container.
To make things "safer" and fail early with errors rather than mysterious
compatibility problems, I am adding explicit versions to the
lib{cephfs,rados,rbd}-devel-* packages. Now if the container can't find
these packages it will fail rather than partially upgrade the ceph
packages.

testing: simplify package update, but require matching versions

---

README.md

Now that we are adding more versions of the library that will compile with ceph versions that vary, we should add documentation of what versions are supported.
There's also a few general updates to the readme that come with this.

readme: Add a version table

---

testing/containers/ceph/Dockerfile

Bump the golang version to 1.14.7. Go 1.14 is now the older supported
version, with the recent release of Go.

testing: use supported golang version in ci container images

---

internal/callbacks/callbacks.go
rbd/diff_iterate.go
rbd/watchers_mimic.go

Since the index of the registered callbacks is basically only used as `void*`/`unsafe.Pointer`, it makes more sense and code simpler, if the index type is uintptr instead of a simple int.

callbacks: use uintptr instead of int as index

---

rbd/rbd_nautilus.go
rbd/rbd_nautilus_test.go

The sparsify function can be used to make an image sparse by replacing
runs of zeros with holes. This change adds a wrapper for the basic
rbd_sparsify function and accompanying tests.
Fixes: #280

rbd: add Sparsify implementing rbd_sparsify

---

internal/cutil/cutil.go
internal/cutil/cutil_test.go
rbd/diff_iterate.go
rbd/watchers_mimic.go

rbd: remove unnecessary C wrapper functions

---

cephfs/file.go
cephfs/file_test.go
internal/cutil/iovec.go
internal/cutil/iovec_test.go

First patch adds a new type to internal/cutil for managing iovec's from go. I put it here because it seemed generic and out of place just in cephfs and it turns out they are used in rbd (for a couple of aio calls though... not something I'm jumping to add right now).
Second patch adds Preadv and Pwritev to the File type. These allow you to read or write into multiple byte-slice buffers in one call.
Fixes: #259 
Fixes: #258

cephfs: add Pwritev & Preadv File methods

---

Makefile
cephfs/admin/bytecount.go
cephfs/admin/doc.go
cephfs/admin/fsadmin.go
cephfs/admin/fsadmin_test.go
cephfs/admin/subvolume.go
cephfs/admin/subvolume_test.go
cephfs/admin/subvolumegroup.go
cephfs/admin/subvolumegroup_test.go
cephfs/admin/volume.go
cephfs/admin/volume_octopus.go
cephfs/admin/volume_octopus_test.go
cephfs/admin/volume_test.go
entrypoint.sh

Fixes: #341 (it's a beginning at least)
Fixes: #202 
This is a RFC / design review PR for a new package, named "cephfs/admin", that aims to provide a simple API for administrating CephFS volumes. The focus is on functions needed to create/remove/update/view subvolumes and subvoulme groups. As noted in the linked issue, the first consumer is expected to be ceph-csi but the aim to have a general API that can be consumed by any Go code that wants to manage cephfs volumes. Ideally, this module should be both more efficient and more convenient than shelling out to the `ceph` cli tool.
Functions currently covered:
* CreateSubVolume
* CreateSubVolumeGroup
* ListSubVolumeGroups
* ListSubVolumes
* ListVolumes
* RemoveSubVolume
* RemoveSubVolumeGroup
* ResizeSubVolume
* VolumeStatus
I'll try and …

Add a CephFS Administrative sub-package

---

rbd/rbd_nautilus_test.go
rbd/snapshot_nautilus.go

GetParentInfo() currently requires the caller to specify the
string length for various attributes it returns. If the
specified string length is less than required, it can return
ERANGE error. Replacing it with a new function which avoids
this.
Fixes: #347

rbd: add a new version of GetParentInfo()

---

rbd/rbd_nautilus_test.go
rbd/snapshot.go
rbd/snapshot_nautilus.go
rbd/snapshot_octopus.go
rbd/snapshot_octopus_test.go
rbd/snapshot_test.go

Added wrappers for 
1. rbd_snap_get_name()
2. rbd_snap_get_id()
3. rbd_snap_get_timestamp()
4. rbd_snap_set_by_id()
Fixes: #354

rbd: add snapshot ID related functions

---

cephfs/admin/fsadmin.go
cephfs/admin/fsadmin_test.go
cephfs/admin/volume.go
cephfs/admin/volume_test.go

Add the EnumerateVolumes who's return value can also be treated like a mapping between ID<->names and used to convert between them. 
The enumeration is based on `ceph fs dump` like JSON, but for implementation only. The dump feature itself is not currently exported in a raw form.
Fixes #356

cephfs admin: add EnumerateVolumes for getting volumes names and ids

---

cephfs/admin/fsadmin.go
cephfs/admin/subvolume.go
cephfs/admin/subvolume_test.go
cephfs/admin/subvolumegroup.go
cephfs/admin/subvolumegroup_test.go

* Add a SubVolumePath function (fixes #355 )
* Add a SubVolumeGroupPath function (fixes #358 )

cephfs admin: add getpath functions for subvolume and subvolumegroup

---

cephfs/admin/bytecount.go
cephfs/admin/subvolume.go
cephfs/admin/subvolume_test.go
cephfs/admin/timestamp.go
cephfs/admin/timestamp_test.go

Fixes: #363
Add the SubVolumeInfo function, returning SubVolumeInfo type. There are two customization worth noting, the TimeStamp type is added to deal with the difference between Go JSON defaults for time.Time and ceph's, and the use of a placeholder type to unmarshal the value of the "bytes_quota" field, which can either be a string "infinite" or a numeric value. This maps well to the previously created interface, but interfaces can't unmarshal themselves. The placeholder type helps with this conversion. See commit msg for more details.

cephfs admin: add subvolume info function

---

cephfs/admin/subvolume.go
cephfs/admin/subvolume_octopus.go
cephfs/admin/subvolume_octopus_test.go
cephfs/admin/subvolume_test.go
cephfs/admin/subvolumegroup.go
cephfs/admin/subvolumegroup_test.go

Add support for subvolume and subvolumegroup snapshots. Add support for SubVolumeSnapshotInfo.
This PR builds on top of the work in PR #366 please review and merge that first.

cephfs admin:  subvolume snapshot support

---

cephfs/admin/clone.go
cephfs/admin/clone_test.go
cephfs/admin/fsadmin.go
cephfs/admin/fsadmin_test.go
cephfs/admin/response.go
cephfs/admin/response_test.go
cephfs/admin/subvolume.go
cephfs/admin/subvolume_octopus.go
cephfs/admin/subvolume_octopus_test.go
cephfs/admin/subvolume_test.go
cephfs/admin/subvolumegroup.go
cephfs/admin/subvolumegroup_test.go
cephfs/admin/volume.go
cephfs/admin/volume_octopus.go
cephfs/admin/volume_octopus_test.go
cephfs/admin/volume_test.go

Clone support for cephfs subvolumes.
It comes with a response handling refactor and the addition of Force remove methods.
As part of cloning I had to deal with numerous differences between ceph versions and these are inter-codename differences. IOW, some "nautilus" releases behave one way, some newer "nautilus" release behave another way. At the time of this writing some changes have been back-ported into nautilus but not yet into octopus.
This is all to say that various changes/refactoring/whatnot that made this a bigger PR are due to issues found testing and working with what's ended up being the most complicated part of this module.

cephfs admin: subvolume clone support

---

cephfs/admin/subvolume.go
cephfs/admin/subvolume_test.go

Some versions of ceph return a list of supported features for a
subvolume. On versions that don't return this field the list will always
be empty.

cephfs admin: add support for a list of features in SubVolumeInfo

---

cephfs/admin/workflow_test.go

This PR builds on the changes in PR #373 please review that PR first.
This doesn't touch every call in cephfs admin, but does try to act like a real application, or set of applications would: reading and  writing data as well as using the api to create and manage subvolumes, snapshots, and clones.
With this test we ought to be able to detect any behavior changes in ceph or changes/regressions in our api.

cephfs admin: add a workflow test to check call behaviors

---

README.md

Adds v0.6.0 to library versions matrix.

readme: document v0.6.0 and supported ceph versions

---

.github/mergify.yml

Unfortunately it is not recommended to use a regular expression to check
for the CI status of multiple tests. In case some tests do not run and
fail to report the status, Mergify will not know something is wrong and
PRs might get merged.
The only way to make sure all status checks have passed successfully, is
to list them all separately.
See-also: https://docs.mergify.io/conditions.html#validating-all-status-check

Include all status checks explicitly in the Mergify configuration

---

rados/ioctx.go
rados/ioctx_nautilus.go
rados/ioctx_nautilus_test.go

Add implements section to doc comment for SetNamespace.
Add GetNamespace implementing rados_ioctx_get_namespace
Fixes: #267

rados: add GetNamespace implementing rados_ioctx_get_namespace

---

.github/workflows/stale.yml

For stale issues: stale after 30 days, close after 14 days of stale
Details: https://github.com/actions/stale/blob/main/README.md

Add configuration for Github stale action

---

internal/callbacks/callbacks.go
internal/callbacks/callbacks_test.go

The former code assumed a LIFO usage, and otherwise always produced
collisions.  This change uses unique IDs instead, that as a
side-effect might make debugging easier.

callbacks: replace index with unique ID

---

rados/rados.go
rados/rados_nautilus.go
rbd/rbd.go
rbd/rbd_test.go

In order to provide the ability to do thick provisioning of RBD images,
Image.WriteSame() can be used. The `rbd` commandline utility calls the
rbd_writesame() function when an image is created with the
`--thick-provision` option.
See-also: ceph/ceph-csi#1675

Add rbd_writesame()

---

cephfs/file.go
cephfs/file_test.go
cephfs/path.go
cephfs/path_test.go

The cephfs packages gains new functions:
* File method Truncate implementing ceph_ftruncate
* Truncate implementing ceph_truncate
As a bonus, while adding the above I noted the coverage on path.go was nearly 100% but just missing an error condition check for Statx, so I added it here.
Fixes: #264

cephfs: add functions for path and file Truncate

---

cephfs/admin/flags.go
cephfs/admin/fsadmin.go
cephfs/admin/subvolume.go
cephfs/admin/subvolume_test.go
cephfs/admin/subvolumegroup.go

Recently, the subvolume remove json for the mgr's cephfs command grew a retain snapshots flag. Because we don't really want a zillion functions in go-ceph for all possible flags, the subvolume remove feature now comes with:
* RemoveSubVolume
* ForceRemoveSubVolume
* RemoveSubVolumeWithFlags
The latter is new and takes a new type SubVolRmFlags. It is expected that the caller create a new SubVolRmFlags and set "Force" or "RetainSnapshots" as needed. All other variants that only take a force flag continue to only have a Remove<Foo> and ForceRemove<Foo> functions in order to avoid boolean control arguments.
Fixes #385

cephfs admin: add extended set of flags for subvolume remove function(s)

---

.github/workflows/main.yml

Mimic is not a supported build target in v0.7 and as such there's no need to keep testing it any more.

ci: remove "mimic" from testing matrix

---

.github/mergify.yml

The test case is gone from the CI. Remove it from the merigify config too.

github: remove mergify rule checking for mimic as we have removed it

---

.github/mergify.yml

The "extended-review" label indicates that review is likely to take
an extended period of time and for bots (or even humans) to not automatically take
a PR.
This avoid the need to preemptively mark a PR as changes needed or
give a false impression with a "do-not-merge" label, which has a subtle
lack-of-quality implication.

github: do not automatically merge on "extended-review" label

---

cephfs/admin/subvolume_test.go

Now that the new year has arrived this test assertion has started to
fail. This is because, although I anticipated the year would eventually
change and used GreaterOrEqual, the argument order is wrong. My excuse
is that I find the argument order in testify's Equal function confusing,
it causes me to assume other functions in testify are also confusing
(even when it's the "normal" order) and/or I copy and pasted from an
Equal line and didn't change the args (both are true!).
Instead of allowing any old year, we assume that the clocks where the
test are run are in sync enough that the current year is correct for
the assertion (thanks for the suggestion Sven).
Happy new year, go-ceph!

cephfs admin: fix reversed args in greater-or-equal assertion

---

internal/timespec/timespec.go
rados/errors.go
rados/ioctx.go
rados/omap.go
rados/operation.go
rados/operation_flags.go
rados/operation_test.go
rados/read_op.go
rados/read_op_test.go
rados/write_op.go
rados/write_op_test.go
rados/write_step.go

This is a redo of what was found in #315. Please see below for a more detailed list of what is different from that PR.
The Ceph librados API provides a suite of API calls for interacting with "operations". These are sets of steps that put together perform a batch operation atomically. The API flow goes a bit like (in pseudocode):
```
op = create_op()
assert_version(op, ...)
read_omap(op, ...)
read_data(op, ...)
operate(op)
```
In go-ceph we were already using some of these API calls, but we did not expose the batch nature of them. Rather, we would wrap it all in one Go function and effecitvely hid this. While convenient if all you want to do is read or write the omap or "touch" an object, it prevents the user of go-ceph from using the "full power" of the APIs ceph provides.
My goal with …

rados: add a framework for read and write operations (new attempt)

---

micro-osd.sh

This is an attempt to fix #423.

ci: run ceph-osd in foreground during mkfs

---

cephfs/file_xattr.go
cephfs/file_xattr_test.go
cephfs/path_xattr_test.go

Ceph issue https://tracker.ceph.com/issues/46084 has been fixed with
backports to nautilus and octopus. Re-enable the relevant test data
and fix up the tests to match.
Fixes: #207

cephfs: enable test cases with ceph issues that have been fixed

---

internal/cutil/aliases.go

This change adds a new pointer alias CPtr, that should always only
contains pointers to C allocated memory and should always used for
such pointers in order to keep them separate from Go pointers more
easily. This is helpful, since only CPtr are allowed to be stored in
C allocated memory, and Go pointers can only be passed to C functions
if they don't point to memory not containing Go pointers again, that
is all pointers in such memory must be CPtr.
The change also adds aliases for C.malloc and C.free that return and
accept the CPtr type as a little safety measure.
Additionally there are some useful constants defined.

cutil: add general C type, function and const aliases

---

rbd/rbd_test.go

Ceph issue https://tracker.ceph.com/issues/43178 has been fixed for
a while with backports. No reason not to enable these test cases now.
Fixes: #207

rbd: enable test cases with ceph issues that have been fixed

---

rbd/group.go
rbd/group_test.go

These are the simplest "rbd global" functions that allow managing groups w/o interacting also with images.
Add GroupCreate implementing rbd_group_create
Add GroupRemove implementing rbd_group_remove
Add GroupRename implementing rbd_group_rename
Add GroupList implementing rbd_group_list
Naming was <noun><verb> to better match other functions in rbd
like NamespaceCreate, etc. even though I don't prefer that
ordering ;-).
Fixes: #416

rbd: Add initial group management functions

---

rbd/mirror.go
rbd/mirror_test.go

Add functions:
* SetMirrorMode implementing rbd_mirror_mode_set
* GetMirrorMode implementing rbd_mirror_mode_get
* MirrorEnable implementing rbd_mirror_image_enable2
* MirrorDisable implementing rbd_mirror_image_disable
* MirrorPromote implementing rbd_mirror_image_promote
* MirrorDemote implementing rbd_mirror_image_demote
* MirrorResync implementing rbd_mirror_image_resync
* MirrorInstanceId implementing rbd_mirror_image_get_instance_id
For now, these mirroring related functions are only supported on octopus
builds. Right now the demand is for snapshot based mirroring, which is
new in octopus. We can always relax this in the future and add the
necessary support for nautilus, for journaling only based mirroring.
Part of: #393  - however not all functions are added in this PR.

rbd: add an initial set of basic mirroring functions

---

rbd/mirror.go

RBD was misspelled as RDB. While I was there I made the comments
for both constants more consistently worded.

rbd: fix typo in comment & improve comment consistency

---

rbd/mirror.go
rbd/mirror_test.go

Added two functions:
1. GetMirrorImageInfo()
2. GetImageMirrorMode()
Fixes: #379

rbd: add functions to fetch mirroring status of a RBD image

---

cephfs/admin/flags.go
cephfs/admin/subvolume_test.go

The json key sent to retain snapshots on subvolume remove was misspelled
and had a dash in it rather than an underscore. Fix the incorrect key
and add a test, that needs to be able to run on version of cephfs w/o
snapshot retention, and verifies that flag does the correct thing.
Octopus does not have snapshot retention while newer versions of nautilus does. :-\
See also: #451

cephfs admin: fix the json sent when flag RetainSnapshots is set

---

rbd/rbd.go
rbd/rbd_test.go

As per go-ceph issue #427, and a discussion in #399 this change and
test ensure that the cephIoctx helper function, that extracts the
C.rados_ioctx_t from a Go rados.IOContext, never returns a nil/null
C type.
As these are always "programming errors" panicking is reasonable
behavior for this case.

rbd: test that cephIoctx helper panics when fed invalid inputs

---

rbd/group.go
rbd/group_test.go

Add functions for managing and listing images in rbd groups.
* Add GroupImageAdd implementing rbd_group_image_add
* Add GroupImageRemove implementing rbd_group_image_remove
* Add GroupImageRemoveByID implementing rbd_group_image_remove_by_id
* Add GroupImageList implementing rbd_group_image_list
* Add GetGroup implementing rbd_get_group
Fixes #417

rbd: add group image functions

---

micro-osd.sh

This is another attempt to fix #423.

ci: wait before starting ceph-osd

---

internal/cutil/ptrguard.go
internal/cutil/ptrguard_test.go

PtrGuard is a type that allows to store a Go pointer (that is a pointer pointing to memory allocated by the Go runtime) in C memory (that is memory allocated by C, with malloc() for example). The pointer passing rules of cgo don't allow Go code to store Go pointer in C memory. However, there is a compiler directive for functions that tells the GC not to touch a pointer stored in a uintptr argument until the function returns. PtrGuard takes advantage of this by calling such a function in a Goroutine that stores the uintptr containing the Go pointer in the provided C memory and then waits for a release signal (implemented via a mutex). After the release signal is received, the C memory is overwritten with NULL and the function returns, which makes the pointer accessible to the GC again. …

cutil: add PtrGuard for storing Go pointers in C memory

---

rbd/group_snap.go
rbd/group_snap_test.go

Functions to implement rbd group snapshots:
* Add GroupSnapCreate implementing rbd_group_snap_create
* Add GroupSnapRemove implementing rbd_group_snap_remove
* Add GroupSnapRename implementing rbd_group_snap_rename
* Add GroupSnapList implementing rbd_group_snap_list
* Add GroupSnapRollback implementing rbd_group_snap_rollback
* Add GroupSnapRollbackWithProgress implementing rbd_group_snap_rollback_with_progress
Comes with tests.
Fixes: #418 
<s>Based on #447 - please review and merge that first.</s>

rbd: add functions to support rbd group snapshots

---

testing/containers/ceph/Dockerfile

This change sets GODEBUG to cgocheck=2 which enables complete checking of pointer handling (at some cost in run time). See [here](https://golang.org/cmd/cgo/#hdr-Passing_pointers) for more details.
The CI for this PR will fail first, because we are violating the rules already at some places. Let's fix these until we can merge this PR, and then we will have an insurance, that it will not happen again.
Depends on #441

ci: add GODEBUG=cgocheck=2 to the test container environment

---

README.md

Add the recently released v0.8.0 to the table.

readme: document v0.8.0 and the ceph versions it supports

---

cephfs/path_test.go

cephfs: add a missing userMount() to tests

---

.github/workflows/main.yml

In order to run CI jobs also on PRs that are based on other PRs, this
change adds the pattern 'pr/**' to the tested base branches.  That
means, if PRs are pushed that are based on branches that start with
pr/... these PRs are also get tested. So, if we - by convention - push
PRs to branches like for example pr/ansiwen/myfix42, then all PRs
that are not based on master but another PR get tested as well.
For reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

CI: add branch pattern 'pr/**' to PR test workflow

---

rbd/mirror.go
rbd/mirror_test.go

Make some of the types we added to support constants for the mirroring meet the Stringer interface.
This adds string conversion for MirrorMode, ImageMirrorMode, and MirrorImageState.
Fixes: #470

rbd: add String methods to some mirroring constants

---

Makefile
cephfs/cephfs_test.go
cephfs/file_test.go
cephfs/mount_perms_mimic_test.go
cephfs/path_test.go
cephfs/permissions_test.go
entrypoint.sh
micro-osd.sh

The external mount point was mainly used for stat prior to a Stat function being part of go-ceph's cephfs package. Now that we have Statx, we can replace the need for the external mount and os.Stat.
These changes remove the use of the external fuse mount, the useMount helper function, and then finally the set up code for fuse in the test container and makefile.

cephfs: remove external fuse mount fs from tests

---

.github/workflows/main.yml
Makefile
entrypoint.sh
micro-osd.sh
testing/containers/ceph/Dockerfile

This change implements the makefile target `test-multi-container` to run the test in a multi-container setup. This will allow us to implement tests that require two ceph clusters, like mirroring.
Two containers are started with micro-osd and then pause. Then a third container runs the tests against these ceph instances. (At the moment only against the first of them, because we don't have multi-cluster tests yet.) To share the configurations, the test container mounts the ceph data volumes from both of the ceph containers.
In case of octopus (and later) the test container also sets up and tests mirroring from container test_ceph_a to test_ceph_b, so that it can used in the tests later on.
Depends on: #468

CI: implement a multi-container test setup

---

entrypoint.sh
rbd/errors.go
rbd/mirror.go
rbd/mirror_test.go
rbd/rbd_test.go

This function is added, along with required return types and some helper
functions, to support fetching the global mirroring status component
that makes up a major part of `rbd mirror image status` command's
output.
Part of: #460

rbd: add GetGlobalMirrorStatus implementing rbd_mirror_image_get_global_status

---

Makefile

A fix for running the multi container test, as well a small workflow improvement for both rules.

Small multi-container makefile tweaks

---

Makefile
README.md
entrypoint.sh
testing/containers/ceph/Dockerfile

After examining the rbd command line tool more closely I determined that we could replace the current use of fuse for the rbd mirroring test setup with `rbd import` and `rbd export` commands. Thus we can drop the dependency on fuse (again).
See commit messages for some additional details.
Depends on #476

ci: remove the need for rbd-fuse from the test setup

---

README.md

readme: document v0.9.0 and the ceph versions it supports

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore

This change adds configurations for running the development environment in a container, as supported by VSCode or GitHub Codespaces.

contrib: add configuration for devcontainer

---

entrypoint.sh
internal/commands/response_test.go

Some tests were not run, because entrypoint.sh used a fixed list of
package, which is easily forgotten to update.  This change creates the list
of packages dynamically.
Also it fixes the tests of the response package.

test: make sure that all tests are run

---

Makefile
testing/containers/ceph/Dockerfile

We're adding a fair amount of octopus (and later) only features now, and
at the time of this writing, pacific is already out. Stop defaulting to
nautilus and default to octopus instead.

makefile: use "octopus" as our default ceph version

---

internal/cutil/aliases.go
internal/cutil/cslice.go
internal/cutil/cslice_test.go
rados/omap.go
rados/write_op.go
rbd/mirror.go

This change uses slices on top of C allocated array memory in order
to have a simple (no pointer arithmetic) and safe (boundary-checked)
access to its elements.
Based on #428 

rados: remove pointer arithmetic on c-buffers

---

.gitignore

a file name .build.octopus gets created everytime the repoository is opened into the dev cointainer, adding it in gitignore will solve this issue.
Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

add build.octopus to gitignore

---

entrypoint.sh
micro-osd.sh

For better or worse, unlike Go, shell does not have a standard formatting style.
Add a vim modeline that should match the basic current formatting style of the
scripts. This ought to help fellow vim users when editing the scripts.

entrypoint.sh: add a vim modeline to help set formatting parameters

---

.github/mergify.yml

Tests are running against Ceph Pacific and passing, so this can be
marked as a required CI status.
dpulls handles dependencies between PRs, once the status is marked with
success, the requirements have all been merged. Prevent merging when
dpulls is in a failed state.

github: require Pacific and dpulls to pass before merging

---

rbd/rbd.go

Small fix that prevented building on MacOS.

rbd: fix argument type of rbd_writesame call

---

testing/containers/ceph/Dockerfile

Sometimes the version in the RPM repository don't match the version
of the base image. This change updates the packages before installing
the libraries in order to make them match.

tests: update packages to keep ceph common and libraries in sync

---

rbd/rbd.go
rbd/snapshot.go
rbd/snapshot_test.go

This is a change to what is described in #176.
Transfer of the Set function in the Snapshot.go file to the SetSnapshot() function in rbd.go
- rbd: add SetSnapshot re-implementing rbd_snap_set on image type
- rbd: add deprecation comment to snapshot.Set method

 Method snapshot.Set has side-effects on Image state

---

Makefile
cephfs/admin/fsadmin.go
common/commands/doc.go
common/commands/interfaces.go
doc.go
internal/commands/commands.go
internal/commands/trace.go
rbd/admin/admin.go
rbd/admin/admin_test.go
rbd/admin/common_test.go
rbd/admin/doc.go
rbd/admin/msschedule.go
rbd/admin/msschedule_complex_test.go
rbd/admin/msschedule_test.go

Depends on #463 please review that first.
Resolves #396.
This adds the basic package which is similar to cephfs admin, but has a few improvements on that design (I hope).
The APIs covered are only related to rbd mirror snapshot scheduling as that is a need the ceph csi project has in the short(er) term.
In the future this package could also contain functions for managing rbd trash purge schedules, rbd task management, a few other assorted functions, and whatever gets added to the mgr (or any ceph service using the "json command api") in the future.

Add rbd admin package

---

rgw/admin/bucket.go
rgw/admin/bucket_test.go
rgw/admin/errors.go
rgw/admin/quota.go
rgw/admin/quota_test.go
rgw/admin/radosgw.go
rgw/admin/radosgw_test.go
rgw/admin/usage.go
rgw/admin/user.go
rgw/admin/user_test.go
rgw/admin/utils.go

This commit introduces support for user and bucket quota on the rgw
admin ops API.
Co-authored-by: Irek Fasikhov malmyzh@gmail.com
Co-authored-by: Quentin Perez qperez42@gmail.com
Signed-off-by: Sébastien Han <seb@redhat.com>

rgw/admin: add quota support

---

Makefile
testing/containers/ceph/Dockerfile

If the make variable USE_CACHE is set, the test container will mount
the /go directory from a named volume that is reused in following
test runs, so that go dependencies don't have to be installed again.

tests: add USE_CACHE variable to enable go packages cache

---

README.md

I forgot to do this last week after the release. Oops. :-)

readme: document v0.10.0 and the ceph versions it supports

---

rados/conn.go
rados/object_iter.go
rados/rados.go

In an urge to revisit and enable more checking rules in revive I've started converting some of the "old" c_* names to variable names that don't voliate Go conventions.
This PR fixes up all files in rados _except_ for rados/ioctx.go. These changes are fairly mechanical [1] and mind-numbing so to make the reviews simpler I'm splitting up the work over time. ioctx.go has a lot of convention violations so I'm saving that for a different PR.
[1] - It was done 90% by script.

rados: fix some naming convention violations

---

Makefile

These changes convert instances of the `go` and `gofmt` commands in the makefile to variables.
Then we add a new variable "flag" `USE_GOCO=1` to enable running go commands through a container image. This is inspired by recent work     to enable development containers for VSCode, but is more aimed at     vim/cli users like myself who want to compile the code via makefile     rules and make use of vim's quickfix feature without having to have ceph     libs or, more importantly, the right version of the ceph libs, locally.
Full example: `make build test-bins USE_CACHE=1 USE_GOCO=1`

makefile: add a flag to run go commands via a container

---

cephfs/cephfs.go
cephfs/cephfs_test.go

Add a ReadConfigFile function that accepts a path to a config file. This will be especially handy when we need to connect to multiple ceph clusters from one (go-ceph test) function.

cephfs: add ReadConfigFile implementing ceph_conf_read_file 

---

rgw/admin/mock.go
rgw/admin/radosgw.go
rgw/admin/user_test.go

Partially solve https://github.com/ceph/go-ceph/issues/508.
I'm saying "partially" since @phlogistonjohn we need to see if we keep `Debug` or not.

rgw/admin: add an interface around the HTTP Client and mocking

---

rbd/encryption.go
rbd/encryption_test.go

Ceph pacific added image encryption (https://docs.ceph.com/en/latest/rbd/rbd-encryption/).  This change adds support to the encryption format api which enables the encryption by creating the encryption header in the image.  
Note that as part of this change I have updated the Makefile to support Pacific by default.  I hope that's ok.
Signed-off-by: Effi Ofer <effio@il.ibm.com>

rbd: support image encryption in pacific

---

rados/ioctx.go

Following up on the work in PR #520 this fixes numerous violations of the naming conventions in Go converting "c_blah" to "cBlah" (mostly*).
The changes were made uing "gofmt" but I tried to rebase them (many many times) in order to have them grouped logically by function rather than spinkled hither and thither.
* there are a few "cblah" when blah is not a word, but an initialism :-)

rados: fix various naming convention issues

---

rgw/admin/README.md
rgw/admin/bucket_test.go
rgw/admin/quota_test.go
rgw/admin/radosgw.go
rgw/admin/radosgw_test.go
rgw/admin/usage_test.go
rgw/admin/user_test.go

Instead of implementing our own logging let's the consumer implement
their own potential debug for each HTTP requests.
Closes: https://github.com/ceph/go-ceph/issues/508
Signed-off-by: Sébastien Han <seb@redhat.com>

rgw/admin: remove Debug field from API type

---

rbd/mirror.go
rbd/mirror_test.go

This change adds an iterator type to fetch infos for all images in a pool with `rbd_mirror_image_info_list()`. It uses the same interface as `MirrorImageGlobalStatusIter`.
Resolves: #482

rbd: implement bindings for rbd_mirror_image_info_list

---

cephfs/admin/fsadmin_test.go
cephfs/admin/mgrmodule.go
cephfs/admin/mirror.go
cephfs/admin/mirror_test.go
cephfs/admin/mirror_workflow_test.go
cephfs/admin/workflow_test.go
internal/commands/response.go
micro-osd.sh

Add functions to configure and inspect cephfs mirroring to cephfs admin package.
The first few patches add a few adjustments to non-API code in preparation for testing cephfs mirroring code.
Support for setting up the cephfs mirroring daemon is added to micro-osd. This is disabled on nautilus and octopus.
Functions are added that configure needed ceph mgr modules.
Functions to set up cephfs mirroring and mirror directories are added.
Two functions for inspecting the state of mirroring are added. I know of one additional function that I did not expose. The json returned by that function is a bit more complex and I thought the PR was already too big. I will look into it for a follow up PR.
Basic tests for the JSON parsing, as well as a large "end to end" test that actually sets up mirroring …

cephfs admin: add initial support for cephfs mirroring

---

cephfs/admin/mirror.go

A small follow up to PR #519  that makes the naming a tad more sensible.

cephfs admin: mirror type naming fix

---

rgw/admin/user.go
rgw/admin/user_test.go

The stat information gives idea about current storage consumption.
Include that info to the user struct
[Updated} also added url for `user cap` in the api request
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

rgw/admin: include stat information to User Struct

---

rbd/mirror.go

`Close()` is basically a no-op in the `defer` use case, and reuse of iterators I would strongly discourage from. The existence of this method gives the wrong impression that there are resources, that need to be freed. Also the error return value is unusual and actually dead code. It seems like the `Close()` method is a leftover from an earlier implementation.

rbd: deprecate Close() method of MirrorImageGlobalStatusIter

---

rbd/mirror.go
rbd/mirror_test.go

This change exports the functions that fetch the list chunks. It's a pretty thin wrapper around the `rbd_mirror_image_*_list` functions. The only difference is that a max value 0 will not return an empty slice, but a slice with _all_ items.
Depends on: #523 

rbd: export mirror image list functions

---

rbd/metadata.go
rbd/options.go
rbd/rbd.go
rbd/snapshot.go

Depends on PR #535 
More naming cleanups. One cleanup needed to be skipped as the public fields of a public struct have underscores.
A few cases were in the vars in a function. I think these can be safely modified as the _names_ of the function arguments and return values are not part of the public API. (They do show up in the docs though)
Yell at me if you think I'm wrong.

rbd: fix various naming convention issues

---

cephfs/file_test.go

cephfs test was disabled because there was bug in ceph related to ftruncate
the ceph bug is resolved, so re-enabling the cephfs test
Closes: https://github.com/ceph/go-ceph/issues/439
Signed-off-by: parth-gr <paarora@redhat.com>

cephfs: re-enabled the skipped test for cephfs

---

cephfs/permissions_test.go

Fix up variable names that don't meet Go standards.
Yeah, more of these.

cephfs: naming conventions: fix names in cephfs permissions test

---

rados/command_test.go
rados/rados_test.go
rbd/rbd_test.go

More naming cleanups.  This time mostly in the rbd test functions.
I think these changes should have fewer exceptions then the previous patches did but as these are coming out of a backlog I can't 100% guarantee it. :-)

rbd: fix various naming convention issues in tests

---

.gitignore
Makefile
entrypoint.sh

The first change adds a state file for mirroring setup to the entrypoint. It helps avoid doing extra work.
The second change adds a whole family of test-containers-* rules. The role
meant to be used directly "test-containers-test" brings up the
required dependencies once, and will reuse them on subsequent runs.
The targets "test-containers-kill" and "test-containers-clean" will
remove just the ceph containers and all dependencies respectively.
The change may look big, and I did shorten some lines, thus lengthening
the makefile vertically, but the logic is basically the same as before.
One can continue using "test-multi-container" and it should behave
pretty much as before, but outside the CI when working on code or
testing things out using the more granular rules can help speed things
up. …

Makefile: improve working with multi containers for devs

---

docs/api-stability.md

Lets work out an API stability document with this PR.

docs: add a API stability document

---

.github/workflows/main.yml
cephfs/path_test.go
cephfs/statx_test.go

Depends on: #560 
These changes fix minor issues repeating the tests run on an existing cluster in cephfs.
Then we update the CI rules to allow us to share (mirror-enabled) ceph container     instances. Use this to test both non-ptrguard and prtguard test runs     while dropping the (now redundant) non-mirror-enabled ceph + tests    container run.

worfklows: update CI rules

---

entrypoint.sh

This might help a bit with flakey tests.

entrypoint: show return values of tests

---

Makefile
entrypoint.sh

By default we want our ci to run with the `ceph_preview` tag (see the recent [api-stability policy](https://github.com/ceph/go-ceph/tree/master//docs/api-stability.md)).
In the Makefile and entrypoint.sh we support setting NO_PREVIEW in order to skip the ceph_preview tag and test only non-preview api calls.
This pr currently contains a patch with a "canary" test that intentionally fails when build with the preview tag. This is make sure things are being plumbed through correctly. It should be dropped from the PR prior to merge.

Use the ceph_preview tag by default in our CI

---

rgw/admin/caps.go
rgw/admin/caps_test.go
rgw/admin/errors.go

Added two apis AddUserCap() and RemoveUserCap() to add/remove the
capabilities from RGW user.
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

rgw/admin: add apis for handling UserCap

---

rbd/admin/imagespec.go
rbd/admin/imagespec_test.go
rbd/admin/task.go
rbd/admin/task_test.go

- rbd admin: add type ImageSpec to work with rbd task api 
ImageSpec type has been added to work with rbd task api.
It consists of optional pool & namespace and image name/id.
[pool/][namespace/]image[Name/id].
- rbd admin: add unit tests for ImageSpec 
- rbd admin: add rbd task [list|cancel|remove|trash remove|flatten]` apis 
These functions let one add various rbd tasks that are done
asynchronously in the background. Also added tests for the same.

rbd admin: add rbd task api functions

---

.github/workflows/main.yml
contrib/apiage.py
contrib/implements/internal/implements/gosrc.go
contrib/implements/internal/implements/inspector.go
contrib/implements/internal/implements/json_report.go
contrib/implements/internal/implements/report.go
contrib/implements/main.go
docs/api-status.json
docs/api-status.md
entrypoint.sh
rbd/rbd.go
rbd/snapshot.go
testing/containers/ceph/Dockerfile

(Edited)
This PR adds the following:
* New features to `implements` to scan the go-ceph code, find and report on stable/preview/deprecated APIs
* A new contrib script `apiage.py` that can
* compare the report from `implements` to a persistent managed copy of the api report & detect issues
* update the persistent copy with new apis, etc
* (re)generate a human-readable markdown files summarizing the preview and deprecated apis
* Updates to the ci to run `implements` and `apiage.py` to check for issues (when possible)
* An initial version of the persisted `docs/api-status.json` and `docs/api-status.md` files
Because we require something in the table, I've marked the new preview apis from pr #571 as new in v0.12.0 (obvious) and expected stable version v0.13.0. If there are issues with this …

contrib: tooling to help manage API stability & aging

---

internal/cutil/ptrguard.go

Some linters complain about the old expression. Although purely cosmetic, I came up with a simpler expression, that does not create warnings.

ptrguard: simplify pointer size assert

---

cephfs/admin/mirror_workflow_test.go

Fixes #574
This is a workaround for the common test flake:
```
=== RUN   TestMirroring
mirror_workflow_test.go:63:
Error Trace:    mirror_workflow_test.go:63
Error:          Received unexpected error:
rados: ret=-95, Operation not supported:
"Module 'mirroring' is not enabled (required by command 'fs snapshot
mirror enable'): use `ceph mgr module enable mirroring` to enable it"
Test:           TestMirroring
```
at even though we've certainly requested the mode be enabled the mgr
has apparently not fully processed the request and the module is
not yet available. We add a half-second sleep after each call
to hopefully give the mgr time enough to completely enable the module.
A future improvement would be to poll the mgr until we know it is ready to
use the cephfs mirroring module, but that …

cephfs admin: add sleeps after mgr module is enabled (workaround)

---

.github/pull_request_template.md
Makefile
contrib/apiage.py
docs/api-stability.md
docs/development.md
entrypoint.sh

Fixes #590 
Fixes #593
Adds defaults to apiage to derive a simple version of the policy in code, deriving from the current git tag.
Adds makefile rules for contributors to use.

contrib: encode a simple version of the api stability policy into apiage

---

rados/omap.go
rados/read_op.go
rados/write_step.go

In #581 we discovered, that we are actually violating the pointer passing rules in some places. For the write buffer of the `writeStep`s this change uses a `PtrGuard`, while the return parameters of `GetOmapStep`s are allocated in C memory.
Related: #584

rados: Make "operation" code comply to pointer passing rules

---

docs/development.md

This PR fixes a typo in development docs:
s/udpate/update/g

docs: api-update typo

---

cephfs/admin/mgrmodule.go
cephfs/admin/mirror_workflow_test.go

Add (internal only) support for getting the enabled modules for the manager. Use that to try and make the test case more robust.

cephfs admin: wait for mirroring module

---

docs/api-status.json
docs/api-status.md
internal/cutil/aliases.go
rados/write_op_preview.go
rados/write_op_preview_test.go

This PR adds binding for [`rados_write_op_cmpext`](https://people.redhat.com/bhubbard/nature/default/rados/api/librados/#c.rados_write_op_cmpext) RADOS Write operation including unit tests.
Related: ceph/ceph-csi#2148

rados: implement binding for rados_write_op_cmpext

---

docs/api-status.json
docs/api-status.md
rados/read_op_read.go
rados/read_op_read_test.go
rados/read_step.go

This PR adds binding for [`rados_read_op_read`](https://people.redhat.com/bhubbard/nature/default/rados/api/librados/#c.rados_read_op_read) RADOS Read operation including a unit test for it.
It also adds a common `readStep` struct as it was missing.

rados: implement binding for rados_read_op_read

---

Makefile

Since it is usually necessary to rebuild the `implements.json` file when doing a `api-check` or `api-update`, this change always rebuilds it, so that it is not necessary anymore to manually delete the result directory. 

make: always rebuild implements.json

---

testing/containers/ceph/Dockerfile

This issue should have been fixed in ceph-containers already but for
whatever reason we don't seem to be getting the fix.
For now, disable the apache-arrow-centos repo.
Based on: https://github.com/ceph/ceph-csi/pull/2859/commits/8b4c8dc7305ff5ecc99d5805b9f7a31a33068a33

containers: disable a repo to get the ci up and going again

---

docs/api-status.json
docs/api-status.md
rados/rados_write_op_remove.go
rados/rados_write_op_remove_test.go

This PR implements binding for `rados_write_op_remove` RADOS Write operation.

rados: implement binding for rados_write_op_remove

---

docs/api-status.json
docs/api-status.md
rados/rados_read_op_assert_version.go
rados/rados_read_op_assert_version_test.go
rados/rados_write_op_assert_version.go
rados/rados_write_op_assert_version_test.go

This PR implements bindings for:
* `rados_read_op_assert_version` RADOS Read operation
* `rados_write_op_assert_version` RADOS Write operation.

rados: implement binding for rados_{read,write}_op_assert_version

---

rbd/rbd.go

The comments above Read and Write were very old and not up to our
current standards. Update them to be accurate and note that the
offset internal to the image type is not concurrency safe.
This also cleans up some old and unhelpful todos.
- [] Is this a new API? Is this new API marked PREVIEW?

rbd: update doc comments for rbd image Read and Write funcs

---

docs/api-status.json
docs/api-status.md
rados/watcher.go
rados/watcher_test.go

This change implements the bindings for the watch/notify APIs of
librados. Instead of callbacks, the watcher is implemented with more
Go-idiomatic channels. A watcher object exposes two read-only
channels, one to receive the notify events and one to receive
occuring errors.

rados: implement watch/notify APIs

---

common/log/log.go
internal/log/log.go
internal/log/log_test.go

This change adds two log packages.  One for the external go-ceph
consumers under `common/log`, and one for the internal use within the
go-ceph code under `internal/log`.  The external package exports two
functions for consumers, `SetWarnf()` and `SetDebugf()`, that set a
logger for warnings and debug messages respectively. They take a
`log.Printf` compatible function as argument.
The internal package exports these functions as `Warnf()` and `Debugf()`,
which can be used by the go-ceph code to log warnings and debug
messages.

common: implement a common log package

---

docs/api-status.json
docs/api-status.md
rados/rados_set_locator.go
rados/rados_set_locator_test.go

Add wrapper to set locator key for rados IOContext.
Related to #268 and #84
Signed-off-by: Alexander Pücker <alexander.puecker@hetzner.com>

rados: add wrapper to set locator key on IOContext

---

docs/api-status.json
internal/cutil/buffergroup.go
internal/cutil/buffergroup_test.go
rados/omap.go
rados/read_op.go
rados/read_op_omap_get_vals_by_keys.go
rados/write_op.go

This PR is a follow-up to our previous discussion in https://github.com/ceph/go-ceph/pull/629#discussion_r800915702 .
All RADOS bindings that handle OMap keys now use their "more flexible" librados versions that consume byte strings with explicit lengths instead of expecting them to be null-terminated.
I have done a bit of refactoring too -- creating new C-allocated arrays to store the key sizes seemed like too much boilerplate. To that end I have added `cutil.GoCSLenSlice` that handles byte arrays and size arrays in one go.
Also, it seems that some of the `*Step` structs were unnecessary: these particular C functions in librados make copies of their args anyway, so it seems there is no need to keep them around for longer in the `*Step` structs...
I've tried to split this PR into multiple …

rados: use omap v2 bindings

---

docs/api-status.json
docs/api-status.md
rgw/admin/errors.go
rgw/admin/link.go
rgw/admin/link_test.go

This change implements link/unlink bucket APIs of
rgw/admin.
Related to #645 
Signed-off-by: wanggangfeng <gfengwong@gmail.com>

rgw/admin: add suport for link/unlink bucket

---

docs/api-status.json
docs/api-status.md
rgw/admin/bucket.go
rgw/admin/caps.go
rgw/admin/errors.go
rgw/admin/link.go
rgw/admin/quota.go
rgw/admin/subuser.go
rgw/admin/subuser_test.go
rgw/admin/usage.go
rgw/admin/user.go
rgw/admin/user_test.go
rgw/admin/utils.go
rgw/admin/utils_test.go

These commits add support for the subuser calls in the rgw admin interface.
Closes #521.
Implementing the subuser commands required a restructuring of the way the objects are serialized to API parameters. The way this was done is up to review and I am open to changes.
This is a breaking change, since the User type changes (by adding detailed type information for the fields related to subusers to support type safe parsing from the json responses). The API calls on the wire may change as well (as go-ceph now only serializes those parameters that are actually supported by the Ceph RGW Adminops API, not all parameters that are set in the "mirror" object on the go-ceph side).
See also the related discussion: #641.

Add support for the subuser calls in the rgw admin interface

---

Makefile
common/admin/nfs/admin.go
common/admin/nfs/doc.go
common/admin/nfs/export.go
common/admin/nfs/export_test.go
internal/commands/response.go
internal/commands/response_test.go
micro-osd.sh

The initial set of APIs are mostly in place, but the tests are untested.
Fixes: #628

nfs: admin APIs for managing nfs exports

---

docs/api-status.json
docs/api-status.md

Because implements tool only looked at certain packages so far, there were no entries for the new package `common/log` in the api-status files.

common/log: add missing api-status entries

---

.github/workflows/main.yml

Because of the flaky tests sometimes the non-required test cancels the required one, which makes the flaky tests even more annoying.

CI: disable fail-fast in test-suite

---

contrib/apiage.py
contrib/implements/main.go
entrypoint.sh

The implements tool and the api-update target ignored a couple of packages. Instead of adding each package explicitly, I changed the logic, so that all packages but the internal ones are scanned.

implements: analyze all but internal packages

---

rados/ioctx.go
rados/rados_test.go

:wave: We've been using a patch that's similar to this in production for a while now, which has helped with our internal tooling to clean up broken MPUs created by RGW. Ideas welcome on how I could go about testing the changes to ListObjects. I don't know of a way to create an object with a null char in the key short of getting a new CLS function committed.

List oids null

---

go.mod
go.sum

The older version has some bugs fixed in newer releases. These issues
were exposed on patches not yet merged. We can take this now and
rebase those more complex patch series afterwards.

go-ceph: require a newer version of testify

---

.github/dependabot.yml

Dependabot can automatically create PRs for packages that have have a
new release. By depending on recent versions of the consumed packages,
the result of the OpenSSF scorecard will improve.
See-also: https://deps.dev/go/github.com%2Fceph%2Fgo-ceph/
Doc: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

github: add Dependabot for managing versions in go.mod

---

contrib/implements/internal/implements/gosrc.go

The implements API checker should not treat a function as exported if it's type is not exported.
Certain APIs, such as those pertaining to JSON require public methods on unexported types. Since the type is not exported `implements` should not worry about it.

implements: a public function's type must be exported too

---

.devcontainer/devcontainer.json
.github/workflows/main.yml
Makefile
entrypoint.sh
internal/cutil/sync_buffer.go
internal/cutil/sync_buffer_memcpy.go

Let's make PtrGuard the default, so we can remove the non-PtrGuard code in a later release.

cutil: enable PtrGuard by default

---

.github/workflows/main.yml
Makefile
cephfs/admin/clone_test.go
cephfs/admin/fsadmin_test.go
cephfs/admin/subvolume_test.go
cephfs/admin/volume.go
cephfs/admin/volume_test.go
micro-osd.sh
rbd/admin/msschedule_complex_test.go
rgw/admin/bucket_test.go
testing/containers/ceph/Dockerfile

Fixes #649 
Fixes #657 
Depends on: #674 
This PR adds initial support for Ceph 'quincy'. 
There are a few sub-topics here: let me know if you think it's better if I split them out as separate PRs.
* Adding quincy to the build & CI
* Updating the micro-osd.sh to be easier to test/hack on
* Fixing issue starting radosgw in micro osd
* Fixing cephfs admin API change (keeping it backwards compatible)
* Fixing an incorrect usage in the rbd api (a regression in quincy but one we didn't have to hit)
* Making it easier to test against dev versions of ceph in the future
* Adding skips for broken/unstable tests
Some tests currently don't work right on quincy and these have been disabled by skip-test calls. If this PR is merged the skips will be filed as issues and we can track and resolve them …

Add quincy support to our CI tests

---

testing/containers/ceph/Dockerfile

The Go 1.18 release was done in march 2022 and so we should
continue to use the older of the two supported releases which
is now Go 1.17.x.

containers: update the go version used in the CI container

---

docs/api-status.json
rbd/snapshot_rename.go
rbd/snapshot_rename_test.go

This change creates a wrapper method for `rbd_snap_rename` so that Go clients can access that functionality. 
Let me know if there's anything that needs to be changed about this implementation! Once this is satisfactory, I would love to backport to v0.13 and v1.14.

rbd: expose rbd_snap_rename to Go clients

---

.github/pull_request_template.md
common/admin/nfs/admin.go
common/admin/nfs/export.go
common/log/log.go
contrib/implements/internal/implements/gosrc.go
docs/api-stability.md
docs/api-status.json
docs/development.md
rados/rados_read_op_assert_version.go
rados/rados_set_locator.go
rados/rados_write_op_assert_version.go
rados/rados_write_op_remove.go
rados/rados_write_op_setxattr.go
rados/read_op_omap_get_vals_by_keys.go
rados/read_op_read.go
rados/watcher.go
rbd/snapshot_rename.go
rgw/admin/link.go
rgw/admin/subuser.go

implements: don't rely on PREVIEW comments but on `ceph_preview` tag

---

cephfs/admin/fsadmin.go
cephfs/admin/metadata.go
cephfs/admin/metadata_test.go

Exports below APIs:
SetMetadata,
GetMetadata(),
RemoveMetadata(),
ForceRemoveMetadata() and
ListMetadata()
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

cephfs: add subvolume metadata APIs

---

cephfs/admin/snapshot_metadata.go
cephfs/admin/snapshot_metadata_test.go

Exports below APIs:
SetSnapshotMetadata,
GetSnapshotMetadata(),
RemoveSnapshotMetadata(),
ForceRemoveSnapshotMetadata() and
ListSnapshotMetadata()
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>
Additional information to reviewers/Maintainers:
~~This PR needs https://github.com/ceph/ceph/pull/46086 which is not merged upstream yet, but the cmd schemas will mostly be same.~~
Update: https://github.com/ceph/ceph/pull/46086 is merged upstream now.

cephfs: add subvolume snapshot metadata APIs

---

cephfs/admin/mgrmodule.go
docs/api-status.json

As per the planned removal in api-status

cephfs admin: remove deprecated EnableModule, DisableModule funcs

---

rbd/rbd_nautilus.go

This removes the limit on the max buffer size `GetImageNames` is willing to pass to `rbd_list2`, which is somewhat arbitrary and is too small for large clusters. `GetImageNames` will continue to start with a small buffer size and retry with a larger buffer if `rbd_list2` returns ERANGE (just without a cap on the max buffer size it's willing to go to).
I considered creating a new API method in which max buffer size is configurable, but ultimately it seemed much simpler/cleaner to me to just keep the current method and kill the cap entirely. My team has experimented with a no-cap version of `GetImageNames` (since the capped one fails on our clusters which have many thousands of volumes), and it hasn't had any issues. However, if there is a subset of users for whom having the cap is …

rbd: don't cap the buffer size used in GetImageNames

---

docs/api-stability.md

Signed-off-by: riya-singhal31 <rsinghal@redhat.com>

fix: fixed few typos

---

cephfs/admin/clone_test.go

The code causing this issue has been packported to pacific and blocks
the CI. We need to temporarily disable for pacific as well.

CI: also disable TestCancelClone for pacific

---

cephfs/admin/snapshot_metadata_test.go

> no new variables on left side of :=
Avoid assigning new value to existing variable.

cephfs/admin: Fix compile errors

---

.github/workflows/main.yml

We will (most probably) remove non-ptrguard code before the next
release. Let's skip the tests already now, because they double the
likelihood of failing flaky tests.

CI: remove non-ptrguard tests

---

Makefile

`:=` is not capable of accepting values(for variables) from execution environment. Therefore replace `:=` with `?=` for completeness.

Makefile: Use `?=` for initial variable definitions

---

rados/conn.go
rados/ioctx.go

Because we have a finalizer configured for Conn that cleans up Ceph resources, it's important that we don't let it get GC'd before anything that depends on it has been cleaned up. Since clients are free to hold a reference to an IOContext without maintaining a reference to the underlying Conn, we hold such a Conn reference within the IOContext to signal this dependency to the Go GC.
Fixes https://github.com/ceph/go-ceph/issues/569.

rados: Make sure Conn isn't GC'd while it has dependant IOContexts.

---

docs/api-status.json
docs/api-status.md
rados/alloc_hint_flags.go
rados/ioctx_set_alloc_hint.go
rados/ioctx_set_alloc_hint_test.go
rados/write_op_set_alloc_hint.go
rados/write_op_set_alloc_hint_test.go

Signed-off-by: Quentin Devos <4972091+Okhoshi@users.noreply.github.com>
Add support in go-ceph:
- rados_set_alloc_hint2
- rados_write_op_set_alloc_hint2
Closes #697 
I'm not sure how I'm supposed to test the Allocation Hint, especially since I'm not aware of a way to check the Allocation hints set on a file, and that the functions never return errors.

rados: Implement rados_set_alloc_hint2

---

entrypoint.sh

Following the mirroring setup there used to be a file named `token` holding the bootstrap token left out in sources. We could instead provide the token via standard output and display it for any further debugging purpose.

entrypoint: Store bootstrap token in variable

---

go.mod

Updates the Go version of the module with `go mod tidy -go 1.17`,
which also adds some explicit requirements in order to support lazy
module loading.

go-ceph: bump Go version of module to 1.17

---

entrypoint.sh
rbd/mirror.go
rbd/mirror_nautilus.go
rbd/mirror_nautilus_test.go
rbd/mirror_test.go

I've implemented mirroring support that is compatible with Nautilus clusters. It's a fairly different API from the one exposed for Octopus, since the underlying librbd interface changed so much between them.
It needs to be clear in the documentation that these methods are only available when using the `nautilus` build tag. One way to do that is just mention it in the documentation comments for all of them (not very DRY, but simple), another is to add a new section to the API docs, similar to the existing "preview" section, which would box off those methods into their own category. What approach would you like to take?

rbd: add mirroring support for nautilus

---

rgw/admin/bucket.go

This change add a new bucket struct field , so we can use rgw.admin.API.GetBucketInfo() to get a bucket's num_shards.
```
radosgw-admin bucket stats --bucket test
{
"bucket": "test",
"num_shards": 11,    <<<<    NumShards  *uint64 `json:"num_shards"
"tenant": "",
"zonegroup": "d9d22c42-ea25-44df-bded-506b5d64bc82",
... 
}
```

Rgw/admin: add num_shards to  bucket struct field

---

docs/api-status.json
docs/api-status.md
rados/ioctx_pool_alignment.go
rados/ioctx_pool_alignment_test.go
rados/ioctx_pool_requires_alignment.go
rados/ioctx_pool_requires_alignment_test.go

Add support for retrieving whether a pool supports/requires write alignment and its size in bytes.
Fixes #739

rados: add support for retrieving the alignment (stripe) size

---

.github/dependabot.yml

Lower the frequency of updates. The monthly update is documented to
occur on the first of the month, which works better with our
every-other-month release cadence.
Automatically apply the "no-API" label. Do not add a rebase label, which
has not relevance to the go-ceph workflow.
Use the prefix "go-ceph:" which is what we normally use for changes only
to the go.mode, etc.

github: update dependabot configuration to better match go-ceph style

---

cephfs/statx.go

This change follows the upstream deprecation of AT_NO_ATTR_SYNC in
favor of the standard AT_STATX_DONT_SYNC.
Fixes: #741

cephfs: add AtStatxDontSync and deprecate AtNoAttrSync

---

docs/api-status.json
docs/api-status.md
rgw/admin/bucket_quota.go
rgw/admin/bucket_quota_test.go
rgw/admin/errors.go
rgw/admin/keys.go
rgw/admin/keys_test.go
rgw/admin/quota.go
rgw/admin/user.go
rgw/admin/user_bucket.go
rgw/admin/user_bucket_test.go

This change implements 
- listing of user's buckets (also with stats), 
- user credentials management, 
- individual bucket quota APIs 
of rgw/admin.
Related to https://github.com/ceph/go-ceph/issues/653
Signed-off-by: maxharitonov [maxharitonov@gmail.com](mailto:maxharitonov@gmail.com)

Rgw admin more actions

---

.github/workflows/main.yml
cephfs/admin/fsadmin_test.go

Adds GitHub CI jobs for pre-release versions of **quincy** and **pacific** along with **main** development branch.

workflows: Add pre-release targets to ceph version matrix

---

cephfs/admin/metadata.go
cephfs/admin/metadata_test.go
cephfs/admin/snapshot_metadata.go
cephfs/admin/snapshot_metadata_test.go

Now that we have support for testing APIs from pre-release Ceph versions lets convert the current **ceph_ci_untested** tag into
corresponding pre-release version tags.
Depends on: #743

cephfs/admin: Replace 'untested' with pre-release tags

---

cephfs/admin/metadata.go
cephfs/admin/snapshot_metadata.go

All the C functions needed by cephfs/admin package come from
one of the other go-ceph packages (rados, cephfs, etc) there's
no good reason to have this unused import in these files.

cephfs admin: remove unnecessary import C lines

---

Makefile
contrib/apiage.py

Fixes: #718
This change adds a new "fix-versions" mode to apiage.py, as well as the ability to set placeholder version values when adding a new API. The fix-versions mode replaces placeholder versions with real version
numbers. When fixing versions, the --fix-filter-pkg & --fix-filter-func options can be used to narrow down what APIs will be fixed in case not all version placeholder should be fixed to the same values.
In order to simplify the workflow for contributors we'll continue to ask people to run `make api-update` when contributing new APIs. This will record the API in our api-status files. However, it will now use a
placeholder value without a real version number. If a PR is filed and is not accepted before the next scheduled release the maintenance team will not have to ask the …

contrib: add new fix-versions mode to apiage.py

---

.github/workflows/main.yml
.revive.toml

With the newest version of revive there appears to be no way to have it both check all .go files individually and have it properly detect the package-comments rule.
I took the lazy way out and simply disabled the rule in the config file rather than try to do something more complicated.
Fixes: #754

Fix recent revive failures

---

contrib/apiage.py
docs/api-status.md

For those packages without any preview/deprecated APIs we used to include a header despite any content under it. We could instead mention the state in a meaningful sentence.
Fixes: #595

apiage: Do not leave empty sections for packages in markdown

---

README.md

Add a new "Getting in Touch" with the go-ceph team section. This more
closely reflects the reality of our preference for direct async channels
(discussions, issues), indirect async channels (the ceph lists) and then
the sync chat which we really haven't been adhering to for quite some
time.

readme: replace "office hours" with a new contact section

---

docs/hints.md

Based on https://github.com/ceph/go-ceph/discussions/557

docs: add official documentation for how go-ceph does errors

---

Makefile
contrib/apiage.py

Depends on #759 
Fixes: #760 
The intended workflow is to update the Go source code and then run `make
api-promote` which will detect the changes to the ceph_preview tag(s) in
the sources and then promote apis from preview to stable in the
tracking json.
I explicitly do not want apiage.py (or the makefile) to make changes to
the source code. The contributor may or may not want to make changes
incrementally, also some times a preview function may be moved to
another source file. Plus, I simply think this is a job for a human.
But we can avoid having to edit the JSON and markdown files afterward.

apiage: ability to promote apis tracked in JSON from preview to stable

---

cephfs/file.go

cephfs: fix a minor typo in a doc comment

---

common/admin/nfs/export.go
common/admin/nfs/export_sectype_test.go

Ceph is adding a flag to get/set NFS-Ganesha's SecType configuration opiton. This can be used to specify authentication types for an export. These changes only affect struct fields and are fully backwards compatible with existing code. Therefore no API status flags are added to the code.
Test cases added - with api buildtag for ceph main branch.
Fixes: #764

nfs admin: add SecType field

---

docs/release-process.md

Add a reminder to keep get the latest changes from upstream before making the git tag. I was out of date today on my laptop and while I did remember to do it on my own - adding a hint for the future just makes future mistakes a tad less likely.

docs: add a reminder to keep local git in sync before tagging

---

contrib/apiage.py

The apiage script had a few bugs in the new ability to help promote and api from preview to stable. When I tried to use the script for real they raised their ugly heads. This fixes the issues that I saw today.

apiage fixes

---

docs/release-process.md

Rework the front matter in the doc to serve as a checklist to help the release author(s) avoid missing things.
Make the release notes section better match to how that last 4 or so release have been done.

docs: update the release document

---

.github/dependabot.yml

Turns out the dependabot tool can also indicate what github actions we are using can be updated. This can be handy in avoiding the warnings that github throws up all over an action that relies on a deprecated feature. Use a monthly update just like go modules to avoid being pestered all the time.
Blatantly ripped off from the ceph-csi repo.

github: enable dependabot for github-actions

---

.github/workflows/report-stable.yml
Makefile
contrib/apiage.py

Update the workflow "report-stable" to automatically file an issue when stability updates are required. This can then be used as a step the release workflow for go-ceph.
Tested in my own fork of go-ceph.

ci: automatically file issues with api stability changes

---

docs/api-status.json
docs/api-status.md
rados/ioctx_pool_alignment.go
rados/ioctx_pool_alignment_test.go
rados/ioctx_pool_requires_alignment.go
rados/ioctx_pool_requires_alignment_test.go
rados/ioctx_set_alloc_hint.go
rados/write_op_set_alloc_hint.go
rgw/admin/bucket_quota.go
rgw/admin/bucket_quota_test.go
rgw/admin/keys.go
rgw/admin/keys_test.go
rgw/admin/user_bucket.go
rgw/admin/user_bucket_test.go

Two packages had APIs becoming stable for release v0.19, scheduled for 13th December 2022.
Fixes #793

Make preview APIs stable for v0.19

---

rados/alloc_hint_flags.go
rgw/admin/caps_test.go
rgw/admin/link_test.go

These are left overs from [v0.13.0](https://github.com/ceph/go-ceph/releases/tag/v0.13.0), [v0.17.0](https://github.com/ceph/go-ceph/releases/tag/v0.17.0) and [v0.19.0](https://github.com/ceph/go-ceph/releases/tag/v0.19.0) releases where we missed to remove preview tags when following APIs were promoted to stable.
* _API.AddUserCap_ and _API.RemoveUserCap_ in e23ab127c07c0914bbe4f794a28aabf3fee4664f
* _API.LinkBucket_ and _API.UnlinkBucket_ in 9d74c3c2b1a08ad171d14bb78cc59273434030e3
* _IOContext.SetAllocationHint_ in efa832cdd073807010504e7d948c12820b7d832b
Fixes #798

Remove left over `ceph_preview` tags from test related files

---

contrib/apiage.py

Previously, apiage.py just print out a problem count when it found
an unexpected stable api in the new apis file. Now the output displays
something like this:
```
found new unexpected stable apis: API.LeakyBucket
error: 1 problems detected
```
Bonus patches: 
* More standardized formatting
* Convert some general print calls to either warning or info for future enhancements

contrib: better warning for apiage

---

docs/api-status.json
docs/api-status.md
rbd/migration.go
rbd/migration_test.go

This PR adds support for `rbd migration` apis allowing users to migrate images between pools, in the same pool or from an external stream. https://docs.ceph.com/en/pacific/rbd/rbd-live-migration/)
Signed-off-by: Omid Yoosefi [omidyoosefi@ibm.com](mailto:omidyoosefi@ibm.com)

rbd: implement live migration functions

---

.github/pull_request_template.md

Add a new checklist item reminding contributors to run `make api-update` to track new APIs. Add two short paragraphs that cover some of the common things I copy and paste or need to look up when working with contributors' PRs.

github: update PR template with new checklist item and helpful links

---

contrib/apiage.py
docs/api-status.json
docs/api-status.md

First, I fix a small bug in the way apiage.py is generating the markdown.
Then, as of https://github.com/ceph/go-ceph/commit/d6bf51115d8f1075f1dc12887a41274b5dd196f0 we've tried to make API stability less burdensome on contributors by putting in placeholder values in the status files. However, we haven't used it much yet. This change executes `make api-fix-versions` in order to convert the placeholder versions into real version numbers - both for the real reason of tracking the values and also for a more real world test of the apiage feature.

docs: fix version values for new rdb migration APIs

---

cephfs/admin/metadata.go
cephfs/admin/metadata_test.go
cephfs/admin/snapshot_metadata.go
cephfs/admin/snapshot_metadata_test.go
docs/api-status.json
docs/api-status.md

Following APIs are being added as preview APIs after _ceph_pre__* tags are removed with an exception to Pacific where backports are not yet merged.
* FSAdmin.GetMetadata
* FSAdmin.SetMetadata
* FSAdmin.RemoveMetadata
* FSAdmin.ForceRemoveMetadata
* FSAdmin.ListMetadata
* FSAdmin.GetSnapshotMetadata
* FSAdmin.SetSnapshotMetadata
* FSAdmin.RemoveSnapshotMetadata
* FSAdmin.ForceRemoveSnapshotMetadata
* FSAdmin.ListSnapshotMetadata
fixes #752

Add untracked Subvolume and Snapshot metadata APIs in `api-status`

---

docs/api-status.json
docs/api-status.md
rgw/admin/list_bucket_with_stats.go
rgw/admin/list_bucket_with_stats_test.go

Added new function `ListBucketsWithStat` to get **all** buckets of all users info (for admin keys only).
fixes #800

rgw:add "ListBucketsWithStat" function

---

Makefile
testing/containers/ceph/Dockerfile

Execute `make ci-image` on ARM64 machine and produce valid image. Tested on AWS-Graviton machine.

Build arm64

---

.github/pull_request_template.md

The linebreaks within the 2 bottom paragraphs look fine in an editor such as vim, but look odd when viewed as part of the PR on github. Improve the visuals and make it more readable in the github UI by removing linebreaks.
If you view the file through the GH UI it's easier to see the difference than looking at the diff IMO.

github: fix linebreaks in pr template

---

Makefile
cephfs/admin/volume_test.go
cephfs/select_fs.go
cephfs/select_fs_test.go
docs/api-status.json
docs/api-status.md
entrypoint.sh
micro-osd.sh

This PR updates the micro-osd.sh script to host an alternate cephfs filesystem, on pacific and later. 
The entrypoint.sh and makefile are updated to plumb information about the alternate fs to the test suite.
The SelecFilesystem function is added implementing ceph_select_filesystem.
A group of tests, gated by the name of the alternate filesystem being provided, is added, along with API status updates.
Fixes: https://github.com/ceph/go-ceph/issues/262
Fixes: https://github.com/ceph/go-ceph/issues/818
Original-Version-By: "Arvid E. Picciani" <arvid@kraud.cloud>
Original-PR-URL: https://github.com/ceph/go-ceph/pull/819
New or infrequent contributors may want to review the go-ceph [Developer'sGuide](https://github.com/ceph/go-ceph/blob/master/docs/development.md) including the section on how …

cephfs: add SelectFilesystem, a 2nd fs to micro-osd.sh etc, and tests

---

.github/mergify.yml

As noted in the status on github:
```
The configuration uses the deprecated rebase_fallback attribute of the
queue action.
A brownout is planned on February 13th, 2023.
This option will be removed on March 13th, 2023.
For more information: https://docs.mergify.com/actions/queue/
```
Therefore we'll simply drop this attribute.
Internal/CI change.

github: remove deprecated and failing rebase_fallback attribute

---

docs/api-status.json
docs/api-status.md

This change executes `make api-fix-versions` in order to convert the placeholder versions into real version numbers.

docs: fix api versions for new ListBucketWithStat API

---

cephfs/makedirs.go
cephfs/makedirs_test.go
docs/api-status.json
docs/api-status.md

Hello, this PR adds "ceph_mkdirs" implementation (to create path+subpath at once).
Signed-off-by: Damien DALY <maitredede@gmail.com>
- [&check;] Added tests for features and functional changes
- [&check;] Public functions and types are documented
- [&check;] Standard formatting is applied to Go code
- [&check;] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [&check;] Ran `make api-update` to record new APIs

feat(cephfs): implementation of mkdirs

---

Makefile

Hello,
For dev containers, expose the GOPROXY env for faster tests.
Signed-off-by: Damien DALY <maitredede@gmail.com>
- [&check;] Added tests for features and functional changes (N/A: build scripts)
- [&check;] Public functions and types are documented (N/A: no new functions/types)
- [&check;] Standard formatting is applied to Go code (N/A: no new go code)
- [&check;] Is this a new API? Added a new file that begins with `//go:build ceph_preview` (N/A: no new go code)
- [&check;] Ran `make api-update` to record new APIs (N/A: no new api)

build: propagation of GOPROXY env var

---

testing/containers/ceph/Dockerfile

Previously, commit 102616b15852dac174a071012f945d8522a05265 tried to expose GOPROXY env var from developer environment by specifying it as environment variable or build argument to container build process. But using _--build-arg_ to container build command would require the same to be referenced inside Dockerfile/Containerfile so that the following warning can be avoided:
```
[Warning] one or more build args were not consumed: [GOPROXY]
```

Dockerfile: Add missing GOPROXY build argument

---

rados/ioctx.go

This fixes a memory leak that becomes substantial across large pools.

rados: free object list results after listing

---

rgw/admin/usage.go

Added the uid member to the usage type.
We don't need to handle the uid here, as the ceph function handles it in the backend.
Fixes: #758

rgw/admin: Add missing uid member to usage struct

---

cephfs/admin/volume_info.go
cephfs/admin/volume_info_test.go
docs/api-status.json
docs/api-status.md

cephfs/admin: Add API to fetch volume info

---

docs/api-status.json
docs/api-status.md
rbd/mirror_peer_site.go
rbd/mirror_peer_site_test.go

**Description:**
Added some API components of mirror peer site
Fixes: #486

rbd: Add mirror peer site API components

---

cephfs/admin/fsadmin.go
docs/api-status.json
docs/api-status.md

Fixes: #816 
First commit fixes the version numbers in api-status from our recent API additions. I did this before touching the api-status.* to deprecate the New function.
Second commit deprecates the New function.  The New function created a rados connection object but did not expose it via a public api, making it impossible to deterministically sever / clean up the connection. This commit assumes that the patch will be merged prior to the go-ceph v0.21 release so that we can plan to remove the function three versions later (v0.24).  I chose three versions so that it is one release longer than our typical stabilization period as this function has been around for a while.
New or infrequent contributors may want to review the go-ceph [Developer's …

cephfs admin: deprecate the New function

---

docs/api-status.json
docs/api-status.md

Fix the version numbers of some recently added APIs. I hope to land at least one more PR prior to the release, but it's always nice to have small deltas so I can fix what we've already merged now, and then have a small followup fixing the last batch of apis closer to the reelase.

docs: fix version numbers of recently added APIs

---

README.md

No changes to the supported ceph versions.
n/a

go-ceph: update README.md for v0.21.0 release

---

docs/api-status.json
docs/api-status.md
rbd/locks.go
rbd/locks_test.go

Added new locking APIs for the rbd component named `rbd_lock_acquire`, `rbd_lock_break`, `rbd_lock_release`, `rbd_lock_get_owners`, `rbd_is_exclusive_lock_owner` along with supporting TCs.
Fixes: #274 
Fixes: #275

rbd: Add locking rbd APIs

---

cephfs/file_ops.go
cephfs/file_ops_test.go
docs/api-status.json
docs/api-status.md

Added a new API for the cephfs component named `ceph_mknod`.
Fixes: #257

cephfs: Add mknod cephfs API

---

cephfs/file_ops.go
cephfs/file_ops_test.go
docs/api-status.json
docs/api-status.md

Added a new cephfs API named `ceph_futime`
Fixes: #252

cephfs: Add futime cephfs API

---

rbd/mirror_peer_site.go

**Description:**
Removed the `LastSeen` property of MirrorPeerSite struct as it is not being set/updated anywhere by the ceph API.
Fixes: #870 

rbd: Remove redundant LastSeen property from MirrorPeerSite struct

---

micro-osd.sh

`mon addr` config option expects value in the following [format](https://docs.ceph.com/en/latest/rados/configuration/mon-config-ref/#minimum-configuration):
_< ip-addr >:< port >_
Extract host ipv4 address and mention it with default 6789 port as `mon addr` config option value.
fixes #847

micro-osd.sh: Use ipv4 address for `mon addr` configuration

---

cephfs/file_ops.go
cephfs/file_ops_test.go
docs/api-status.json
docs/api-status.md

Added a new cephfs API named `ceph_futimens`
Fixes: #253

cephfs: Add futimens cephfs API

---

cephfs/file_ops.go
cephfs/file_ops_test.go
docs/api-status.json
docs/api-status.md

Added a new cephfs API named `ceph_futimes`
Fixes: #254

cephfs: Add futimes cephfs API

---

docs/hints.md

Add some prose to the hints doc on how to use our docs convention to map a C/command line api to a go-ceph api.
Note how to make use of a {Mon,Mgr}Command API JSON-command without go-ceph code.
Note how apis start as preview before becoming stable.
Fixes: #872 (at least the call for improved docs part)
n/a
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for …

docs: add some docs on how to find apis

---

rgw/admin/bucket.go
rgw/admin/bucket_test.go

The request header in GetBucketPolicy(), was not passing policy in its
header, so the response received Bucket than the actual policy.
fixes #882

rgw/admin: fix getbucketpolicy api

---

cephfs/admin/workflow_test.go
cephfs/cephfs_test.go
contrib/implements/internal/implements/gosrc.go
rados/rados_test.go
rgw/admin/radosgw.go
rgw/admin/subuser_test.go
rgw/admin/user_test.go

chore: remove refs to deprecated io/ioutil

---

rbd/rbd_nautilus_test.go
rbd/snapshot_nautilus.go

When a parent image has been removed, it will linger in the trash until all siblings are gone. The image is not accessible through it's name anymore, only through its ID.
The ImageSpec that is returned by Image.GetParent() now contains the Trash boolean and the ImageID to identify if the image is in the trash, and use OpenImageById() to access the removed parent image.
Related-to: ceph/ceph-csi#4013

rbd: include details for parent image in the trash

---

.github/workflows/main.yml
Makefile
cephfs/admin/fsadmin_test.go

With the Ceph Reef release imminent, we're a bit overdue to add it to our CI. However, the risk of being a little late is lowered by the fact that we have our tests regularly running against ceph main branch.
However, once the release is done the divergence between the two will increase over time and so I think it's good to get this done soon.

go-ceph: add Ceph Reef CI jobs

---

testing/containers/ceph/Dockerfile

Currently the tests on the released reef image fails due to an RPM transaction error when updating nfs-ganesha. Since go-ceph doesn't need ganesha packages to be up-to-date to ensure that lib{cephfs,rados,rbd}-devel are installed we _temporarily_ disable ganesha repo when running yum update.
See also, discussion in #910 
Testing infra only change.

containers: workaround for ganesha package error on reef

---

.github/workflows/stale.yml

Enable stale bot to mark PRs stale and eventually close stale PRs. I had tried to manually do this in the past with nice comments but I forget to do it and trying to be nice was unrewarding. I find a bunch of old PRs in the list a distraction and don't want to have to think about them or try to follow up on them. I want to be generous to PR authors so PRs can be inactive for 60 days and one has 3 weeks to unstale the PR.
Workflows only change.

workflows: enable stale bot for PRs

---

rgw/admin/bucket.go

RGW/admin: add tenant to bucket struct field
This change adds a new bucket struct field, so we can use rgw.admin.API.GetBucketInfo() to get a bucket's tenant.
```
$ radosgw-admin bucket stats --bucket "tenant0/qb001"
{
"bucket": "qb001",
"num_shards": 11,
"tenant": "tenant0",
```
Signed-off-by: Dmitry Kvashnin <dm.kvashnin@gmail.com>

RGW/admin: add tenant to bucket struct field

---

.github/workflows/main.yml

By placing actions/checkout before actions/setup-go(as suggested in https://github.com/actions/setup-go/issues/281) we could avoid the following warning message:
> Warning: Restore cache failed: Dependencies file is not found in /home/runner/work/go-ceph/go-ceph. Supported file pattern: go.sum
fixes #917

workflows: Move actions/checkout before actions/setup-go

---

rados/rados_test.go

This disables the `TestPingMonitor` until #921 is fixed.

rados: skip TestPingMonitor test

---

cephfs/admin/fsadmin.go
cephfs/file_ops.go
cephfs/file_ops_test.go
docs/api-status.json
docs/api-status.md
rbd/locks.go
rbd/locks_test.go

Fixes #928 
Prepare for the v0.24 release with a batch of API updates. This includes the removal of cephfs admin `New` method.

API updates

---

README.md
docs/older-releases.md

In additition to updating the readme I decided to truncate the table and move the older items to a new historical doc.

docs: update readme supported versions

---

internal/cutil/ptrguard_pinner.go
internal/cutil/ptrguard_test.go

Since Go 1.21 there is a runtime.Pinner API that allows to safely pass structures with embedded Go pointers to C code.  In earlier Go version we know that the garbage collector is non-moving, so it is safe to pass Go pointers to C as well. This change adds two implementations of PtrGuard, one for pre 1.21 that is basically a no-op, and one for 1.21+ that uses runtime.Pinner.

internal: use runtime.Pinner in PtrGuard

---

docs/api-status.json
docs/api-status.md
micro-osd.sh
rgw/admin/info.go
rgw/admin/info_test.go

based on https://github.com/ceph/go-ceph/pull/616

rgw/admin: Add support for /info section

---

docs/api-status.json
docs/api-status.md
rbd/resize.go
rbd/resize_test.go

librbd exposes rbd_resize2, which allows clients to pass in a boolean controlling
whether or not the allocation should be allowed to shrink, and a progress-tracking
callback. This contribution extends go-ceph to be able to call rbd_resize2.
Closes #933 
Signed-off-by: Khayyam Saleem <khayyam.saleem@gmail.com>
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for …

rbd: adds support for librbd rbd_resize2

---

cephfs/errors.go
cephfs/path_test.go

this commit renames ErrNoEntry of cephfs
to ErrNotExist and making it public allowing
other projects to access this.
Signed-off-by: Riya Singhal <rsinghal@redhat.com>

cephfs: made ENOENT a public error

---

.github/workflows/main.yml
entrypoint.sh
testing/containers/ceph/Dockerfile

This change enables core dumps. If a core dump is created, its backtrace is logged with gdb and it is put into the artifacts together with the test executable.
To see it in action, see #923, which creates a core dump and is based on this PR.

CI: enable and collect core dumps in tests

---

.github/workflows/report-stable.yml
docs/api-status.json
docs/api-status.md
micro-osd.sh
rgw/admin/README.md
rgw/admin/radosgw_test.go
rgw/admin/user_test.go

- Fix versions for recent API additions
- Remove a TODO
- Better clarity on S3 credentials inside script

Miscellaneous fixes

---

docs/api-status.json
docs/api-status.md
rgw/admin/user_bucket_quota.go
rgw/admin/user_bucket_quota_test.go

Following APIs have been added to set and get bucket quotas for users.
- _SetBucketQuota_
- _GetBucketQuota_
Credits: [Pavel Boev](https://github.com/R4scal)

rgw/admin: Add support for user bucket quota

---

cephfs/userperm_test.go
internal/cutil/command_input_test.go
internal/cutil/ptrguard_test.go
internal/retry/sizer_test.go
rados/rados_test.go
rbd/diff_iterate_test.go
rbd/group_snap_test.go
rbd/resize_test.go
rbd/sparsify_test.go
rbd/watchers_test.go
rgw/admin/bucket_quota_test.go
rgw/admin/bucket_test.go
rgw/admin/caps_test.go
rgw/admin/info_test.go
rgw/admin/keys_test.go
rgw/admin/link_test.go
rgw/admin/list_bucket_with_stats_test.go
rgw/admin/quota_test.go
rgw/admin/usage_test.go
rgw/admin/user.go
rgw/admin/user_bucket_quota_test.go
rgw/admin/user_bucket_test.go
rgw/admin/user_test.go

revive v1.3.7 added https://github.com/mgechev/revive/pull/966 which checks for unused parameters in function literals. This caused several lint errors in go-ceph code.
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR is …

Code Lint: Fix lint errors caused by revive check for unused parameters

---

rgw/admin/user.go

We accidentally changed the exported API in PR #959

rgw/admin: Fixup for 6f90ce1

---

README.md
docs/api-status.json
docs/api-status.md

- Update api-status files
- Update README
- No new stable APIs

Prepare release v0.26.0

---

.github/workflows/main.yml
Makefile
cephfs/admin/fsadmin_test.go

Add ceph squid CI jobs

---

testing/containers/ceph/Dockerfile

This bumps the Go version of the test container to 1.21.8, which is the oldest supported Go version as of now. The -_go.mod_ file (including an upgrade of its dependencies) is bumped to 1.21 as well.

build: Bump golang version to 1.21

---

cephfs/admin/fs_quiesce.go
cephfs/admin/fs_quiesce_reef_test.go
cephfs/admin/fs_quiesce_test.go
docs/api-status.json
docs/api-status.md

fixes #955 
Depends on https://github.com/ceph/ceph/pull/54485

API for quiesceing io on a subvolume.

---

rbd/encryption_test.go

Add a test to verify that an encrypted volume can be resized to the desired unencrypted size similar to how the rbd command line tool is documented as able to do.
Fixes: #972
Original-Version-By: Will Gorman 
- n/a Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- n/a Ran `make api-update` to record new APIs
The go-ceph project uses mergify. View the [mergify command …

rbd: add a test to verify that encrypted volumes can be resized

---

rbd/resize.go

While building an application with the latest version of go-ceph, the following warning is spit out:
```
In file included from _cgo_export.c:4:
resize.go:7: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/bits/libc-header-start.h:33,
from /usr/include/stdlib.h:26,
from _cgo_export.c:3:
/usr/include/features.h:292: note: this is the location of the previous definition
292 | # define _POSIX_C_SOURCE        200809L
```
When _POSIX_C_SOURCE is already defined, ther is no need to define it again.

rbd: prevent warning about redefining _POSIX_C_SOURCE

---

cephfs/admin/fs_quiesce_reef_test.go
cephfs/admin/fs_quiesce_test.go

With the feature itself getting a backport to upcoming squid release build tags calls for adjustments so that `pre-squid` and `main` CI jobs can run the real tests from _fs_quiesce_test.go_. Until the real squid job is enabled(after ceph squid GA) we could refrain from mentioning `squid` build tag in those related test files.

cephfs/admin: Adjust build tags for subvolume quiescing API tests

---

rbd/rbd.go

It is necessary to determine whether cMaxSnaps is a large 0. Otherwise, the following code will panic
```
// GetSnapshotNames returns more than just the names of snapshots
// associated with the rbd image.
//
// Implements:
//
//	int rbd_snap_list(rbd_image_t image, rbd_snap_info_t *snaps, int *max_snaps);
func (image *Image) GetSnapshotNames() (snaps []SnapInfo, err error) {
if err := image.validate(imageIsOpen); err != nil {
return nil, err
}
var c_max_snaps C.int
ret := C.rbd_snap_list(image.image, nil, &c_max_snaps)
if c_max_snaps < 1 {
return nil, RBDError(ret)
}
c_snaps := make([]C.rbd_snap_info_t, c_max_snaps)
snaps = make([]SnapInfo, c_max_snaps)
ret = C.rbd_snap_list(image.image,
&c_snaps[0], &c_max_snaps)
if ret < 0 {
return nil, RBDError(ret)
}
for i, s := range c_snaps { …
```

rbd: trigger an error on invalid max snaps value

---

README.md
docs/api-status.json
docs/api-status.md
rbd/resize.go
rbd/resize_test.go
rgw/admin/info.go
rgw/admin/info_test.go

Release prep:
* Make rbd Image.Resize2 stable
* Make rgw/admin API.GetInfo stable
* Fixup version numbers for new apis
* Add v0.27 to README version matrix
Fixes: #981 
Side note:
I expect that by the next release of go-ceph the Ceph Squid will be out and we'll add squid to our matrix. With squid coming out I plan on removing nautilus from the test matrix at long last. I don't plan to do any more than that - nautilus build tags will not be proactively removed from the code but after removing it from the test matrix new code will not be required to handle it.

Prepare for release v0.27.0

---

rgw/admin/user_bucket_test.go

rgw/admin: remove unknown user test case from user_bucket_test.go

---

testing/containers/ceph/Dockerfile

With CentOS Stream 8 reaching end of builds phase most of our ceph images are migrating their bases to CentOS Stream 9. Since they come with _curl_ by default in a minimal rpm package we switch to attempt the install by directly linking the binary than the package name. This is due to the conflict between _curl_ and _curl-minimal_ packages in CentOS Stream 9 images.
fixes #994

Dockerfile: Avoid conflict with curl-minimal package

---

testing/containers/ceph/Dockerfile

The centos 8 stream distribution is now EOL and the yum repo mirrors are now offline. However, our CI is designed to test older released versions of ceph where the container images are still using centos 8 stream. Borrow and adapt a line from the ceph-csi project in order to use the centos 8 archives (vault) until either we stop testing these versions of ceph or the ceph project changes the base distro for these release versions.
*Infra only change*

containers: work around centos 8 stream getting archived

---

.gitignore
README.md
docs/api-status.json
docs/api-status.md
rgw/admin/user_bucket_quota.go
rgw/admin/user_bucket_quota_test.go

- Make _{Get,Set}BucketQuota_ APIs stable
- Add v0.28.0 to README matrix
misc
- Add __results_ directory to gitignore
fixes #983

Prepare for release v0.28.0

---

rgw/admin/errors.go
rgw/admin/errors_test.go

There was no Error for comparing the `NoSuchSubUser` code.
Example error: 
```
error(github.com/ceph/go-ceph/rgw/admin.statusError) {Code: "NoSuchSubUser", RequestID: "tx0000074e0db2ad9281b8f-00666abc30-10b8-dev1", HostID: "10b8-dev1-dev"}
```
Reference:
https://github.com/ceph/ceph/blob/8a2a786e62ba1577dde990fef49d18f75efdd023/src/rgw/rgw_common.cc#L106C1-L106C52
The go-ceph project uses mergify. View the [mergify command …

rgw/admin: Add ErrNoSuchSubUser

---

docs/api-status.json
docs/api-status.md
rbd/clone_image_by_id.go
rbd/clone_image_by_id_test.go

RBD image groups can be used to create consistent snapshots of all images that are part of the group. The new rbd_clone4() API makes it possible to create a new RBD image from a single snapshot that was created as part of the group snapshot.
The `rbd_clone4()` API has only just been [backported to Squid for version 19.1.1](https://github.com/ceph/ceph/pull/58044). There are no released container images available yet that contain this new API, only the `ceph-ci/ceph:main` image seems to have it.
New or infrequent contributors may want to review the go-ceph [Developer's Guide](https://github.com/ceph/go-ceph/blob/master/docs/development.md) including the section on how we track [API Status](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status) and the [API Stability …

rbd: add support for CloneImageByID()

---

.github/mergify.yml
.github/workflows/main.yml
Makefile

This PR removes nautilus from our github CI tests and related files.
Fixes: #648
Closes: #1005 
The original plan was to remove nautilus from our test matrix when Ceph
Squid was released. However, while Squid is not released yet, it is very
very soon. In the meantime, CentOS 7 is now EOL and the container images
for nautilus can not be updated. From the Ceph POV nautilus has been
long unsupported and they will not be making any changes to the base OS
for nautilus images. We have no desire to do workarounds for the EOLing
of CentOS7 either. As such we're ending direct support for nautilus a
little early but not by much.
Note that this is only disabling our testing of nautilus - we're not
going to be stripping the build tag from the sources. But we will no
longer require new code to to add …

goodbye nautilus

---

Makefile

Iteration #<span/>2  of #725.
`CEPH_IMG` and `CEPH_TAG` are commonly used to include custom ceph images as base while building go-ceph container images for testing and development purposes.

Makefile: Use `?=` for initial variable definitions(part 2)

---

rgw/admin/bucket.go
rgw/admin/bucket_test.go

The API endpoint for bucket stats includes a `creation_time` field which is not included in the `admin.Bucket` struct. This simply adds the field.
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR is out of date with the …

rgw/admin: add creation time to bucket

---

internal/dlsym/dlsym.go
internal/dlsym/dlsym_test.go
rbd/clone_image_by_id.go
rbd/clone_image_by_id_test.go
rbd/errors.go

The dlsym package provides LookupSymbol() which resolves a named symbol
(like "rbd_clone4") and returns a unsafe.Pointer to it. The caller is
expected to cast the symbol to function that can be called.
Some versions of librbd provide the rbd_clone4 function, and others do
not. Squid will have the function backported in the 1st update, the
initial release of Squid does not have it. This makes checking for the
function based on the named Ceph version impractical.
With the new dlsym.LookupSymbol() function, it is now possible to check
the availability of rbd_clone4 during runtime. If the symbol is not
found ErrNotImplemented is returned, which can be used to detect the
unavailability of the function.
New or infrequent contributors may want to review the go-ceph [Developer's …

Detect `rbd_clone4` support by using `dlsym()`

---

.github/workflows/main.yml

Enable the squid ci job now that the squid RC is available. This won't be required for merge until after the full release.
depends on #1013 
closes #975

workflows: enable squid job

---

contrib/implements/internal/implements/cast.go
contrib/implements/main.go
docs/api-status.json
docs/api-status.md
rados/striper/doc.go
rados/striper/errors.go
rados/striper/read.go
rados/striper/stat.go
rados/striper/stat2.go
rados/striper/stat_info.go
rados/striper/striper.go
rados/striper/striper_test.go
rados/striper/write.go
rados/striper/write_test.go
rados/striper/xattr.go
rados/striper/xattr_test.go
testing/containers/ceph/Dockerfile

Add a new `rados/striper` package that wraps Ceph's libradosstriper. The libradosstriper library builds on top of the librados library to support striping large "objects" over multiple RADOS objects.
Fixes: #1011
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase …

Add new rados/striper package

---

go.mod
go.sum
rados/rados_test.go
rados/rw_op_exec_test.go
rados/striper/striper_test.go
rbd/rbd_test.go

A Blackduck scan has reported "Operational Risks as **High**" for below modules' version.
- bump github.com/gofrs/uuid from _**v4.4.0+incompatible**_ to _**v5.3.0**_
- bump golang.org/x/sys from **_v0.24.0_** to **_v0.25.0_**
Signed-off-by: [Pankaj Thapa] <pk.thapa66@gmail.com>
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact …

go-ceph: Versions upgrade

---

rados/snapshot.go
rados/watcher.go
rbd/snapshot_octopus.go

`len` is already a standard library function. revive [v1.4.0](https://github.com/mgechev/revive/releases/tag/v1.4.0) started looking into function related variables for such standard names as part of redefines-builtin-id rule. Therefore use a different variable name instead of `len`.

Do not use standard names as function arguments

---

rbd/errors.go

Certain operations with RBD can return the C errno EEXISTS. Applications using go-ceph benefit from easily detecting this error.

rbd: add ErrExists as standard error

---

internal/dlsym/dlsym.go

man [dlsym(3)](https://www.man7.org/linux/man-pages/man3/dlsym.3.html) says the following:
> The _GNU_SOURCE feature test macro must be defined in order to obtain the definitions of RTLD_DEFAULT and RTLD_NEXT from <dlfcn.h>.

internal/dlsym: Define _GNU_SOURCE for RTLD_DEFAULT

---

docs/api-status.json
docs/api-status.md
rbd/group_snap.go
rbd/group_snap_info.go
rbd/group_snap_test.go

The new GroupSnapGetInfo function can be used to get a list of the RBD
image snapshots that were created as part of the RBD group snapshot.
This feature is implemented in 2 steps:
1. direct librbd call (only in Ceph **main** branch)
2. modification to use `dlsym`
I hope that makes it easier to understand, and might help others contributing such dynamically loaded functions too.

rbd: implement librbd.rbd_group_snap_get_info

---

docs/api-status.json
docs/api-status.md

Release prep task. Fix versions for one new api.
FWIW no apis become stable in v0.30.

docs: fix version number for new GroupSnapGetInfo api

---

README.md

Add the v0.30.0 release to the versions table. This adds ceph squid to the supported ceph versions in the table.

docs: update README for release v0.30.0

---

cephfs/errors.go
docs/api-status.json
internal/errutil/error.go
internal/errutil/error_test.go
rados/conn.go
rados/errors.go
rados/ioctx.go
rbd/clone_image_by_id.go
rbd/diff_iterate.go
rbd/errors.go
rbd/features.go
rbd/group_snap.go
rbd/metadata.go
rbd/rbd.go
rbd/resize.go
rbd/snapshot.go
rbd/snapshot_nautilus.go
rbd/sparsify.go

A new `internal/errutil.cephError` can be used as a common type to replace all error types that are specific to the different packages (`cephfsError`, `radosError`, `rbdError`). By using the new `cephError` type everywhere, it becomes possible to match `rados.ErrNotFound` and `rbd.ErrNotFound` with the standard `errors.Is()` function.
Some go-ceph functions from the cephfs and rbd packages can return errors generated by the lower-level rados package. In such a case, a caller may need to check for e.g. `rados.ErrNotFound` as well as `rbd.ErrNotFound`, depending on the function that was called. This is prone to errors, as users of go-ceph may not inspect what the go-ceph function does and which error type it could return.
Closes: #1031
New or infrequent contributors may want to review the …

Introduce common cephError type to compare errors between packages

---

testing/containers/ceph/Dockerfile

Work around errors related to protobuf package locations on centos. This is triggered by our squid jobs failing with errors like:
```
22.40  Problem: protobuf-3.14.0-13.el9.i686 from appstream  does not
belong to a distupgrade repository
22.40   - package protobuf-compiler-3.14.0-13.el9.x86_64 from @System
requires protobuf = 3.14.0-13.el9, but none of the providers can be
installed
22.40   - cannot install both protobuf-3.14.0-14.el9.x86_64 from
appstream and protobuf-3.14.0-13.el9.x86_64 from @System
22.40   - cannot install both protobuf-3.14.0-14.el9.x86_64 from
appstream and protobuf-3.14.0-13.el9.x86_64 from appstream
22.40   - cannot install the best update candidate for package
protobuf-3.14.0-13.el9.x86_64
22.40   - problem with installed package …
```

containers: work around protobuf package issues

---

docs/api-status.json
docs/api-status.md
rados/rados_getaddrs.go
rados/rados_getaddrs_test.go

This PR implements binding for rados_getaddrs.
Includes a unit test.

rados: implement rados_getaddrs

---

cephfs/admin/clone.go
cephfs/admin/clone_progress_report_test.go
cephfs/admin/clone_progress_report_unsupported_test.go

Add clone progress report in clone status output
Relevant Ceph PR: https://github.com/ceph/ceph/pull/54620
Ceph Tracker: https://tracker.ceph.com/issues/61904
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR is out of date …

cephfs: add clone progress report in clone status

---

cephfs/errors.go
cephfs/file_fallocate_mode_zero_unsupported_test.go
cephfs/file_test.go

Recent behavioural [changes](https://github.com/ceph/ceph/pull/59725) w.r.t fallocate API calls for corresponding changes in our tests which uses mode 0. In addition to skipping those existing tests we try to cover up the time taken for backports to land in released versions causing CI failures in our pre-release jobs. This has been implemented by creating a new test file intended to be controlled and maintained using required build tags. The new test file can be removed once all the expected backports are available with released versions.
fixes #1044

cephfs: Adjust with the fallocate API changes

---

rbd/snapshot_test.go

Fix for https://tracker.ceph.com/issues/47287 is now available with quincy and above releases. Therefore do not skip `GetSnapTimestamp` API test for an invalid snap ID.
fixes #440 
depends on ceph [v17.2.8](https://github.com/ceph/ceph/milestone/18) GA.

rbd: Remove invalid snap ID test skip

---

cephfs/file_test.go
entrypoint.sh
testing/containers/ceph/Dockerfile

Experimental workaround for ceph ci container build changes. 
Depends on #1043 

[ci] workaround recent changes in ceph's CI built container images

---

README.md
docs/api-status.json
docs/api-status.md
rados/read_op_exec.go
rados/striper/doc.go
rados/striper/errors.go
rados/striper/read.go
rados/striper/stat.go
rados/striper/stat2.go
rados/striper/stat_info.go
rados/striper/striper.go
rados/striper/striper_test.go
rados/striper/write.go
rados/striper/write_test.go
rados/striper/xattr.go
rados/striper/xattr_test.go
rados/write_op_exec.go
rbd/clone_image_by_id.go
rbd/clone_image_by_id_test.go

Release preparation v0.31.0

---

rgw/admin/link.go
rgw/admin/link_test.go

Adding the `new-bucket-name` parameter to `BucketLinkInput` which allows renaming a specific bucket.

rgw/admin: support new-bucket-name for LinkBucket

---

.github/workflows/main.yml

The quincy branch is EOL on the ceph side and there will not be another quincy release so there's no point in having a pre-quincy job now.

workflows: remove pre-quincy job

---

Makefile

Pacific and Quincy releases are already EOL. Therefore remove their corresponding pre-release definitions which are unused and irrelevant these days. On top of all we don't have any CI jobs currently running for _pre-pacific_ and _pre-quincy_.

Makefile: Remove leftovers related to EOL releases

---

rbd/group_snap.go
rbd/sparsify.go

Instead of removing a respective progress callback, DiffIterate extent callback is attempted to be removed.  This leaks the progress callback and on top of that it's quite possible for DiffIterate to be disrupted as cbIndex is not a unique pointer but just an integer ID.
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with …

rbd: fix cleanup of GroupSnapRollback and Sparsify progress callbacks

---

cephfs/admin/fsadmin_test.go
cephfs/admin/volume_test.go
cephfs/file_test.go
internal/util/util.go
rbd/snapshot_test.go

We have at least 3 occurrences where code is duplicated for detecting the underlying Ceph version as a string. Instead, we could have it in common and invoke the corresponding wrapper whenever required.

internal: Use a wrapper to detect server version

---

testing/containers/ceph/Dockerfile

Add another workaround for changes to the ceph container such that the ceph.repo file is deleted from /etc/yum.repos.d. Now we look for a new env var CEPH_IS_DEVEL (which I hope is not going to get changed any time soon) and uses that to decide if we should reinstall the release rpm from the ci system or from the official releases download site.

containers: another workaround for ceph container changes

---

rbd/encryption.go
rbd/encryption_load2.go
rbd/encryption_opt_luks.go

See below for the motivation:
This could be an Go allocated array, but doesn't hurt either.
_Originally posted by @ansiwen in https://github.com/ceph/go-ceph/pull/1061#discussion_r1949471017_
So, here we still allocate Go memory, but it will be referenced in the `cEncryptionData`. ~I guess, wherever that is used, we still have the same problem.~ Ok, I checked, indeed it is used in a "safe" way, that is `cEncryptionData` is not passed directly as a C argument. But still:  I think it would be safer to `malloc` that as well and add it to the free function, because - as it happened to you this time - , it might happen again that someone falsely assumes, it is completely C allocated.
However: We can add that in a follow-up (I can do it) if you want to merge it as is for the release. …

rbd: Memory allocation improvements for EncryptionLoad APIs

---

docs/api-status.json
rbd/list_children_attributes_test.go
rbd/snapshot_nautilus.go

The existing `ListChildren()` API provides only basic information, specifically the pool and image names of a given image’s children. However, in many scenarios, additional metadata is required to fully understand the relationships between images.
This new API extends functionality by leveraging `rbd_list_children3(rbd_image_t image, rbd_linked_image_spec_t *images, size_t *max_images)`, which enables the retrieval of comprehensive details, including:
- Image and pool IDs
- Image and pool names
- Pool namespace
- The trash status of child images
By exposing this additional metadata, the API allows for more informed decision-making when managing child images. Furthermore, modifying the existing `ListChildren()` API would introduce backward compatibility issues, potentially breaking …

rbd: add ListChildrenAttributes Api

---

go.mod

At least one of the requires, `github.com/aws/smithy-go`, bumped its minimum go version requirement to 1.22.
> <h2> Module Highlights </h2>
>
> - github.com/aws/smithy-go: v1.22.3
> - Dependency Update: Bump minimum Go version to 1.22 per our language support policy.

build: Bump go version to 1.22

---

docs/api-status.json
docs/api-status.md
rbd/diff_iterate_by_id.go
rbd/diff_iterate_by_id_test.go

This commit adds support for rbd_diff_iterate3
through DiffIterateByID() which performs
diff interate using snapshot id instead of
snapshot name.
This is useful in cases such as when rbd snapshot is in trash or rbd(group) snapshot in in group namespace.
refer:
- https://tracker.ceph.com/issues/65720
Related ceph PR: ceph/ceph#60844
The go-ceph project uses mergify. View the [mergify command …

rbd: add support for rbd_diff_iterate3 api

---

.github/workflows/main.yml
.github/workflows/report-stable.yml
.github/workflows/stale.yml

Remove the use of unofficial github actions.
Pin the official github actions with the git sha id.
As per: https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/5KWHAST62YAT4P25OO6JYMTRSGSZYPOS/
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github …

workflows: update actions for new ceph org policy changes

---

.github/workflows/main.yml
testing/containers/ceph/Dockerfile

Bump up the default version of the GO version and Ceph version in the container file.
Bump the workflows up to use squid instead of reef when testing alternate Go versions.
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR …

version bumps - container file and workflow

---

go.mod

golang has decided to come up with an [automation](https://github.com/golang/go/issues/69095) to update `go` directive in go.mod from various repositories including x/repos following the release cadence in general. Another interesting and visible change is to explicitly specify the minor version as a suffix to the major version. Thus we are bound to update our `go` directive as we require at least x/sys.

build: Bump go version to 1.23.0

---

rgw/admin/user.go
rgw/admin/user_test.go

The op-mask was not correctly transmitted when creating a user.

rgw/admin: fix op-mask url parameter

---

testing/containers/ceph/Dockerfile

There were two mistakes in the shell that re-installs the ceph-release rpm: (1) the variable was misspelled it should be CEPH_SHA1 not CEPH_SHA and (2) this variable is not set in the environment at all - just the labels. For now, scrape the CEPH_SHA1 value out of the ceph command (which is python, and is fairly easy to scrape). It's a hack on top of a hack but it should get the ci jobs running again.
CI FIX only.

containers: add more hacky shell to fix shaman api query

---

cephfs/directory.go
cephfs/errors.go
cephfs/file.go
cephfs/fscompat.go
cephfs/fscompat_test.go
docs/api-status.json
docs/api-status.md

Fixes: #1088 
I've been meaning to look at this for a long time. Thanks for providing the extra motivation to work on it.
First, fix a few things in the lib that the fstest from Golang digs up.
Then implement fscompat.go a file providing a MountWrapper type that implements fs.FS, as well as private types     that implement fs.File, fs.FileInfo, fs.ReadDirFile, and fs.DirEntry.
The new wrapper classes sit between the Go stdlib and the native CephFS
focused types we provide. Ideally, some of our types would be directly
compatible with the fs interfaces but in many cases our code predates
io/fs. I hope we consider the io/fs use case for any new types added to
the cephfs subpackage in the future - and possibly make compatible
types. But for now I think this is sufficent - especially since the …

cephfs: add compatiblity wrappers for Go's io/fs interfaces

---

rgw/admin/bucket_test.go

The error code returned while trying to remove a non existing bucket changed from `NoSuchBucket` to `NoSuchKey` with tentacle.
fixes #1107

rgw/admin: Fix version check for return code

---

.github/workflows/report-stable.yml
Makefile
contrib/apiage.py

With the third party github actions disabled we directly make use of `gh` command line to create a bare minimum GitHub issue for any API updates to be performed in the next upcoming release.

workflows: Use `gh` command line to create issues

---

.revive.toml
Makefile
common/admin/smb/admin.go
common/admin/smb/admin_test.go
common/admin/smb/cluster.go
common/admin/smb/cluster_test.go
common/admin/smb/doc.go
common/admin/smb/enums.go
common/admin/smb/join_auth.go
common/admin/smb/join_auth_test.go
common/admin/smb/ref.go
common/admin/smb/resources.go
common/admin/smb/resources_test.go
common/admin/smb/result.go
common/admin/smb/result_test.go
common/admin/smb/share.go
common/admin/smb/share_test.go
common/admin/smb/users_groups.go
common/admin/smb/users_groups_test.go
common/commands/interfaces.go
docs/api-status.json
docs/api-status.md
internal/admintest/admintest.go
internal/commands/commands.go
internal/commands/trace.go

Add a new smb admin api.
This should be compatible with the recently added [smb mgr module](https://docs.ceph.com/en/latest/mgr/smb/) in ceph.
Note that the smb module on the ceph side supports a declarative style api where resource specs are the full power interface to use. There are some imperative style apis but we don't need to implement those in this library.
The go-ceph project uses mergify. View the [mergify command …

Add a new smb admin API sub-package

---

common/admin/smb/resources_test.go

We renamed errorMerge to errorPick  but other test failures on main caused me to miss this problem in a prior PR.

admin/smb: fix test that was stil using errorMerge

---

cephfs/file.go
cephfs/file_test.go
cephfs/permissions.go
cephfs/permissions_test.go

Create backward compatible wrappers to cope with the change in ABI for chown family of APIs counting on the implicit type conversion from C.
fixes #1119

cephfs: Use wrappers to handle the ABI changes with chown APIs

---

rgw/admin/bucket_test.go

This reverts commit 39e5ac04dc433bae6c2557e0a8421e8eb6b50072.
The regression itself is getting [fixed](https://tracker.ceph.com/issues/71159) from Ceph side. Therefore the earlier version adjustments won't be required anymore.

Revert "rgw/admin: Fix version check for return code"

---

.github/dependabot.yml

Use grouping with Dependabot to combine all github.com/aws/aws-sdk dependencies in one PR.

ci: update AWS SDK dependencies in a single PR

---

contrib/apicompare.py

Fix typo and avoid duplicate definition to achieve 64 bits file system interface.

contrib/apicompare: Fix bits interface macro definition for CephFS

---

rgw/admin/subuser.go
rgw/admin/user.go
rgw/admin/user_test.go

Add access-key and gen-access-key URL parameters
when creating subusers.
Based on the RGW source code:
https://github.com/ceph/ceph/blob/2b14a6730a7d525fdcd14d23af310045ee4bbd6b/src/rgw/driver/rados/rgw_rest_user.cc#L526-L532
The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` …

rgw/admin: add more options for creating subusers

---

common/admin/osd/admin.go
common/admin/osd/admin_test.go
common/admin/osd/doc.go
common/admin/osd/errors.go
common/admin/osd/osd_blocklist.go
common/admin/osd/osd_blocklist_test.go
docs/api-status.json
docs/api-status.md

- Creates a new OSD admin package under _common/admin_.
- C API, _rados_blocklist_add()_, basically sends mon command behind the scenes and I couldn't find an equivalent API for removal. Therefore the go-ceph APIs introduced here rely on the actual mon commands. 
fixes #598

admin/osd: Create a new OSD admin package to add blocklisting APIs
